export const mobydick = `
    <H2>
      chapter 1. lOOMINGS.
    </H2>
    <P>
      cALL ME iSHMAEL. sOME YEARS AGO&MDASH;NEVER MIND HOW LONG PRECISELY&MDASH;HAVING
      LITTLE OR NO MONEY IN MY PURSE, AND NOTHING PARTICULAR TO INTEREST ME ON
      SHORE, i THOUGHT i WOULD SAIL ABOUT A LITTLE AND SEE THE WATERY PART OF
      THE WORLD. iT IS A WAY i HAVE OF DRIVING OFF THE SPLEEN AND REGULATING THE
      CIRCULATION. wHENEVER i FIND MYSELF GROWING GRIM ABOUT THE MOUTH; WHENEVER
      IT IS A DAMP, DRIZZLY nOVEMBER IN MY SOUL; WHENEVER i FIND MYSELF
      INVOLUNTARILY PAUSING BEFORE COFFIN WAREHOUSES, AND BRINGING UP THE REAR
      OF EVERY FUNERAL i MEET; AND ESPECIALLY WHENEVER MY HYPOS GET SUCH AN
      UPPER HAND OF ME, THAT IT REQUIRES A STRONG MORAL PRINCIPLE TO PREVENT ME
      FROM DELIBERATELY STEPPING INTO THE STREET, AND METHODICALLY KNOCKING
      PEOPLE&RSQUO;S HATS OFF&MDASH;THEN, i ACCOUNT IT HIGH TIME TO GET TO SEA AS SOON
      AS i CAN. tHIS IS MY SUBSTITUTE FOR PISTOL AND BALL. wITH A PHILOSOPHICAL
      FLOURISH cATO THROWS HIMSELF UPON HIS SWORD; i QUIETLY TAKE TO THE SHIP.
      tHERE IS NOTHING SURPRISING IN THIS. iF THEY BUT KNEW IT, ALMOST ALL MEN
      IN THEIR DEGREE, SOME TIME OR OTHER, CHERISH VERY NEARLY THE SAME FEELINGS
      TOWARDS THE OCEAN WITH ME.
    </P>
    <P>
      tHERE NOW IS YOUR INSULAR CITY OF THE mANHATTOES, BELTED ROUND BY WHARVES
      AS iNDIAN ISLES BY CORAL REEFS&MDASH;COMMERCE SURROUNDS IT WITH HER SURF.
      rIGHT AND LEFT, THE STREETS TAKE YOU WATERWARD. iTS EXTREME DOWNTOWN IS
      THE BATTERY, WHERE THAT NOBLE MOLE IS WASHED BY WAVES, AND COOLED BY
      BREEZES, WHICH A FEW HOURS PREVIOUS WERE OUT OF SIGHT OF LAND. lOOK AT THE
      CROWDS OF WATER-GAZERS THERE.
    </P>
    <P>
      cIRCUMAMBULATE THE CITY OF A DREAMY sABBATH AFTERNOON. gO FROM cORLEARS
      hOOK TO cOENTIES sLIP, AND FROM THENCE, BY wHITEHALL, NORTHWARD. wHAT DO
      YOU SEE?&MDASH;pOSTED LIKE SILENT SENTINELS ALL AROUND THE TOWN, STAND
      THOUSANDS UPON THOUSANDS OF MORTAL MEN FIXED IN OCEAN REVERIES. sOME
      LEANING AGAINST THE SPILES; SOME SEATED UPON THE PIER-HEADS; SOME LOOKING
      OVER THE BULWARKS OF SHIPS FROM cHINA; SOME HIGH ALOFT IN THE RIGGING, AS
      IF STRIVING TO GET A STILL BETTER SEAWARD PEEP. bUT THESE ARE ALL
      LANDSMEN; OF WEEK DAYS PENT UP IN LATH AND PLASTER&MDASH;TIED TO COUNTERS,
      NAILED TO BENCHES, CLINCHED TO DESKS. hOW THEN IS THIS? aRE THE GREEN
      FIELDS GONE? wHAT DO THEY HERE?
    </P>
    <P>
      bUT LOOK! HERE COME MORE CROWDS, PACING STRAIGHT FOR THE WATER, AND
      SEEMINGLY BOUND FOR A DIVE. sTRANGE! nOTHING WILL CONTENT THEM BUT THE
      EXTREMEST LIMIT OF THE LAND; LOITERING UNDER THE SHADY LEE OF YONDER
      WAREHOUSES WILL NOT SUFFICE. nO. tHEY MUST GET JUST AS NIGH THE WATER AS
      THEY POSSIBLY CAN WITHOUT FALLING IN. aND THERE THEY STAND&MDASH;MILES OF
      THEM&MDASH;LEAGUES. iNLANDERS ALL, THEY COME FROM LANES AND ALLEYS,
      STREETS AND AVENUES&MDASH;NORTH, EAST, SOUTH, AND WEST. yET HERE THEY ALL
      UNITE. tELL ME, DOES THE MAGNETIC VIRTUE OF THE NEEDLES OF THE COMPASSES
      OF ALL THOSE SHIPS ATTRACT THEM THITHER?
    </P>
    <P>
      oNCE MORE. sAY YOU ARE IN THE COUNTRY; IN SOME HIGH LAND OF LAKES. tAKE
      ALMOST ANY PATH YOU PLEASE, AND TEN TO ONE IT CARRIES YOU DOWN IN A DALE,
      AND LEAVES YOU THERE BY A POOL IN THE STREAM. tHERE IS MAGIC IN IT. lET
      THE MOST ABSENT-MINDED OF MEN BE PLUNGED IN HIS DEEPEST REVERIES&MDASH;STAND
      THAT MAN ON HIS LEGS, SET HIS FEET A-GOING, AND HE WILL INFALLIBLY LEAD
      YOU TO WATER, IF WATER THERE BE IN ALL THAT REGION. sHOULD YOU EVER BE
      ATHIRST IN THE GREAT aMERICAN DESERT, TRY THIS EXPERIMENT, IF YOUR CARAVAN
      HAPPEN TO BE SUPPLIED WITH A METAPHYSICAL PROFESSOR. yES, AS EVERY ONE
      KNOWS, MEDITATION AND WATER ARE WEDDED FOR EVER.
    </P>
    <P>
      bUT HERE IS AN ARTIST. hE DESIRES TO PAINT YOU THE DREAMIEST, SHADIEST,
      QUIETEST, MOST ENCHANTING BIT OF ROMANTIC LANDSCAPE IN ALL THE VALLEY OF
      THE sACO. wHAT IS THE CHIEF ELEMENT HE EMPLOYS? tHERE STAND HIS TREES,
      EACH WITH A HOLLOW TRUNK, AS IF A HERMIT AND A CRUCIFIX WERE WITHIN; AND
      HERE SLEEPS HIS MEADOW, AND THERE SLEEP HIS CATTLE; AND UP FROM YONDER
      COTTAGE GOES A SLEEPY SMOKE. dEEP INTO DISTANT WOODLANDS WINDS A MAZY WAY,
      REACHING TO OVERLAPPING SPURS OF MOUNTAINS BATHED IN THEIR HILL-SIDE BLUE.
      bUT THOUGH THE PICTURE LIES THUS TRANCED, AND THOUGH THIS PINE-TREE SHAKES
      DOWN ITS SIGHS LIKE LEAVES UPON THIS SHEPHERD&RSQUO;S HEAD, YET ALL WERE VAIN,
      UNLESS THE SHEPHERD&RSQUO;S EYE WERE FIXED UPON THE MAGIC STREAM BEFORE HIM. gO
      VISIT THE pRAIRIES IN jUNE, WHEN FOR SCORES ON SCORES OF MILES YOU WADE
      KNEE-DEEP AMONG tIGER-LILIES&MDASH;WHAT IS THE ONE CHARM WANTING?&MDASH;wATER&MDASH;THERE
      IS NOT A DROP OF WATER THERE! wERE nIAGARA BUT A CATARACT OF SAND, WOULD
      YOU TRAVEL YOUR THOUSAND MILES TO SEE IT? wHY DID THE POOR POET OF
      tENNESSEE, UPON SUDDENLY RECEIVING TWO HANDFULS OF SILVER, DELIBERATE
      WHETHER TO BUY HIM A COAT, WHICH HE SADLY NEEDED, OR INVEST HIS MONEY IN A
      PEDESTRIAN TRIP TO rOCKAWAY bEACH? wHY IS ALMOST EVERY ROBUST HEALTHY BOY
      WITH A ROBUST HEALTHY SOUL IN HIM, AT SOME TIME OR OTHER CRAZY TO GO TO
      SEA? wHY UPON YOUR FIRST VOYAGE AS A PASSENGER, DID YOU YOURSELF FEEL SUCH
      A MYSTICAL VIBRATION, WHEN FIRST TOLD THAT YOU AND YOUR SHIP WERE NOW OUT
      OF SIGHT OF LAND? wHY DID THE OLD pERSIANS HOLD THE SEA HOLY? wHY DID THE
      gREEKS GIVE IT A SEPARATE DEITY, AND OWN BROTHER OF jOVE? sURELY ALL THIS
      IS NOT WITHOUT MEANING. aND STILL DEEPER THE MEANING OF THAT STORY OF
      nARCISSUS, WHO BECAUSE HE COULD NOT GRASP THE TORMENTING, MILD IMAGE HE
      SAW IN THE FOUNTAIN, PLUNGED INTO IT AND WAS DROWNED. bUT THAT SAME IMAGE,
      WE OURSELVES SEE IN ALL RIVERS AND OCEANS. iT IS THE IMAGE OF THE
      UNGRASPABLE PHANTOM OF LIFE; AND THIS IS THE KEY TO IT ALL.
    </P>
    <P>
      nOW, WHEN i SAY THAT i AM IN THE HABIT OF GOING TO SEA WHENEVER i BEGIN TO
      GROW HAZY ABOUT THE EYES, AND BEGIN TO BE OVER CONSCIOUS OF MY LUNGS, i DO
      NOT MEAN TO HAVE IT INFERRED THAT i EVER GO TO SEA AS A PASSENGER. fOR TO
      GO AS A PASSENGER YOU MUST NEEDS HAVE A PURSE, AND A PURSE IS BUT A RAG
      UNLESS YOU HAVE SOMETHING IN IT. bESIDES, PASSENGERS GET SEA-SICK&MDASH;GROW
      QUARRELSOME&MDASH;DON&RSQUO;T SLEEP OF NIGHTS&MDASH;DO NOT ENJOY THEMSELVES
      MUCH, AS A GENERAL THING;&MDASH;NO, i NEVER GO AS A PASSENGER; NOR, THOUGH
      i AM SOMETHING OF A SALT, DO i EVER GO TO SEA AS A cOMMODORE, OR A
      cAPTAIN, OR A cOOK. i ABANDON THE GLORY AND DISTINCTION OF SUCH OFFICES TO
      THOSE WHO LIKE THEM. fOR MY PART, i ABOMINATE ALL HONORABLE RESPECTABLE
      TOILS, TRIALS, AND TRIBULATIONS OF EVERY KIND WHATSOEVER. iT IS QUITE AS
      MUCH AS i CAN DO TO TAKE CARE OF MYSELF, WITHOUT TAKING CARE OF SHIPS,
      BARQUES, BRIGS, SCHOONERS, AND WHAT NOT. aND AS FOR GOING AS COOK,&MDASH;THOUGH
      i CONFESS THERE IS CONSIDERABLE GLORY IN THAT, A COOK BEING A SORT OF
      OFFICER ON SHIP-BOARD&MDASH;YET, SOMEHOW, i NEVER FANCIED BROILING FOWLS;&MDASH;THOUGH
      ONCE BROILED, JUDICIOUSLY BUTTERED, AND JUDGMATICALLY SALTED AND PEPPERED,
      THERE IS NO ONE WHO WILL SPEAK MORE RESPECTFULLY, NOT TO SAY
      REVERENTIALLY, OF A BROILED FOWL THAN i WILL. iT IS OUT OF THE IDOLATROUS
      DOTINGS OF THE OLD eGYPTIANS UPON BROILED IBIS AND ROASTED RIVER HORSE,
      THAT YOU SEE THE MUMMIES OF THOSE CREATURES IN THEIR HUGE BAKE-HOUSES THE
      PYRAMIDS.
    </P>
    <P>
      nO, WHEN i GO TO SEA, i GO AS A SIMPLE SAILOR, RIGHT BEFORE THE MAST,
      PLUMB DOWN INTO THE FORECASTLE, ALOFT THERE TO THE ROYAL MAST-HEAD. tRUE,
      THEY RATHER ORDER ME ABOUT SOME, AND MAKE ME JUMP FROM SPAR TO SPAR, LIKE
      A GRASSHOPPER IN A mAY MEADOW. aND AT FIRST, THIS SORT OF THING IS
      UNPLEASANT ENOUGH. iT TOUCHES ONE&RSQUO;S SENSE OF HONOR, PARTICULARLY IF YOU
      COME OF AN OLD ESTABLISHED FAMILY IN THE LAND, THE vAN rENSSELAERS, OR
      rANDOLPHS, OR hARDICANUTES. aND MORE THAN ALL, IF JUST PREVIOUS TO PUTTING
      YOUR HAND INTO THE TAR-POT, YOU HAVE BEEN LORDING IT AS A COUNTRY
      SCHOOLMASTER, MAKING THE TALLEST BOYS STAND IN AWE OF YOU. tHE TRANSITION
      IS A KEEN ONE, i ASSURE YOU, FROM A SCHOOLMASTER TO A SAILOR, AND REQUIRES
      A STRONG DECOCTION OF sENECA AND THE sTOICS TO ENABLE YOU TO GRIN AND BEAR
      IT. bUT EVEN THIS WEARS OFF IN TIME.
    </P>
    <P>
      wHAT OF IT, IF SOME OLD HUNKS OF A SEA-CAPTAIN ORDERS ME TO GET A BROOM
      AND SWEEP DOWN THE DECKS? wHAT DOES THAT INDIGNITY AMOUNT TO, WEIGHED, i
      MEAN, IN THE SCALES OF THE nEW tESTAMENT? dO YOU THINK THE ARCHANGEL
      gABRIEL THINKS ANYTHING THE LESS OF ME, BECAUSE i PROMPTLY AND
      RESPECTFULLY OBEY THAT OLD HUNKS IN THAT PARTICULAR INSTANCE? wHO AIN&RSQUO;T A
      SLAVE? tELL ME THAT. wELL, THEN, HOWEVER THE OLD SEA-CAPTAINS MAY ORDER ME
      ABOUT&MDASH;HOWEVER THEY MAY THUMP AND PUNCH ME ABOUT, i HAVE THE
      SATISFACTION OF KNOWING THAT IT IS ALL RIGHT; THAT EVERYBODY ELSE IS ONE
      WAY OR OTHER SERVED IN MUCH THE SAME WAY&MDASH;EITHER IN A PHYSICAL OR
      METAPHYSICAL POINT OF VIEW, THAT IS; AND SO THE UNIVERSAL THUMP IS PASSED
      ROUND, AND ALL HANDS SHOULD RUB EACH OTHER&RSQUO;S SHOULDER-BLADES, AND BE
      CONTENT.
    </P>
    <P>
      aGAIN, i ALWAYS GO TO SEA AS A SAILOR, BECAUSE THEY MAKE A POINT OF PAYING
      ME FOR MY TROUBLE, WHEREAS THEY NEVER PAY PASSENGERS A SINGLE PENNY THAT i
      EVER HEARD OF. oN THE CONTRARY, PASSENGERS THEMSELVES MUST PAY. aND THERE
      IS ALL THE DIFFERENCE IN THE WORLD BETWEEN PAYING AND BEING PAID. tHE ACT
      OF PAYING IS PERHAPS THE MOST UNCOMFORTABLE INFLICTION THAT THE TWO
      ORCHARD THIEVES ENTAILED UPON US. bUT <I>BEING PAID</I>,&MDASH;WHAT WILL COMPARE
      WITH IT? tHE URBANE ACTIVITY WITH WHICH A MAN RECEIVES MONEY IS REALLY
      MARVELLOUS, CONSIDERING THAT WE SO EARNESTLY BELIEVE MONEY TO BE THE ROOT
      OF ALL EARTHLY ILLS, AND THAT ON NO ACCOUNT CAN A MONIED MAN ENTER HEAVEN.
      aH! HOW CHEERFULLY WE CONSIGN OURSELVES TO PERDITION!
    </P>
    <P>
      fINALLY, i ALWAYS GO TO SEA AS A SAILOR, BECAUSE OF THE WHOLESOME EXERCISE
      AND PURE AIR OF THE FORE-CASTLE DECK. fOR AS IN THIS WORLD, HEAD WINDS ARE
      FAR MORE PREVALENT THAN WINDS FROM ASTERN (THAT IS, IF YOU NEVER VIOLATE
      THE pYTHAGOREAN MAXIM), SO FOR THE MOST PART THE cOMMODORE ON THE
      QUARTER-DECK GETS HIS ATMOSPHERE AT SECOND HAND FROM THE SAILORS ON THE
      FORECASTLE. hE THINKS HE BREATHES IT FIRST; BUT NOT SO. iN MUCH THE SAME
      WAY DO THE COMMONALTY LEAD THEIR LEADERS IN MANY OTHER THINGS, AT THE SAME
      TIME THAT THE LEADERS LITTLE SUSPECT IT. bUT WHEREFORE IT WAS THAT AFTER
      HAVING REPEATEDLY SMELT THE SEA AS A MERCHANT SAILOR, i SHOULD NOW TAKE IT
      INTO MY HEAD TO GO ON A WHALING VOYAGE; THIS THE INVISIBLE POLICE OFFICER
      OF THE fATES, WHO HAS THE CONSTANT SURVEILLANCE OF ME, AND SECRETLY DOGS
      ME, AND INFLUENCES ME IN SOME UNACCOUNTABLE WAY&MDASH;HE CAN BETTER ANSWER
      THAN ANY ONE ELSE. aND, DOUBTLESS, MY GOING ON THIS WHALING VOYAGE, FORMED
      PART OF THE GRAND PROGRAMME OF pROVIDENCE THAT WAS DRAWN UP A LONG TIME
      AGO. iT CAME IN AS A SORT OF BRIEF INTERLUDE AND SOLO BETWEEN MORE
      EXTENSIVE PERFORMANCES. i TAKE IT THAT THIS PART OF THE BILL MUST HAVE RUN
      SOMETHING LIKE THIS:
    </P>
    <P>
      &LDQUO;<I>gRAND cONTESTED eLECTION FOR THE pRESIDENCY OF THE uNITED sTATES.</I>
      &LDQUO;whaling voyage by one ishmael. &LDQUO;bloody battle in affghanistan.&RDQUO;
     </P>
    <P>
      tHOUGH i CANNOT TELL WHY IT WAS EXACTLY THAT THOSE STAGE MANAGERS, THE
      fATES, PUT ME DOWN FOR THIS SHABBY PART OF A WHALING VOYAGE, WHEN OTHERS
      WERE SET DOWN FOR MAGNIFICENT PARTS IN HIGH TRAGEDIES, AND SHORT AND EASY
      PARTS IN GENTEEL COMEDIES, AND JOLLY PARTS IN FARCES&MDASH;THOUGH i CANNOT
      TELL WHY THIS WAS EXACTLY; YET, NOW THAT i RECALL ALL THE CIRCUMSTANCES, i
      THINK i CAN SEE A LITTLE INTO THE SPRINGS AND MOTIVES WHICH BEING
      CUNNINGLY PRESENTED TO ME UNDER VARIOUS DISGUISES, INDUCED ME TO SET ABOUT
      PERFORMING THE PART i DID, BESIDES CAJOLING ME INTO THE DELUSION THAT IT
      WAS A CHOICE RESULTING FROM MY OWN UNBIASED FREEWILL AND DISCRIMINATING
      JUDGMENT.
    </P>
    <P>
      cHIEF AMONG THESE MOTIVES WAS THE OVERWHELMING IDEA OF THE GREAT WHALE
      HIMSELF. sUCH A PORTENTOUS AND MYSTERIOUS MONSTER ROUSED ALL MY CURIOSITY.
      tHEN THE WILD AND DISTANT SEAS WHERE HE ROLLED HIS ISLAND BULK; THE
      UNDELIVERABLE, NAMELESS PERILS OF THE WHALE; THESE, WITH ALL THE ATTENDING
      MARVELS OF A THOUSAND pATAGONIAN SIGHTS AND SOUNDS, HELPED TO SWAY ME TO
      MY WISH. wITH OTHER MEN, PERHAPS, SUCH THINGS WOULD NOT HAVE BEEN
      INDUCEMENTS; BUT AS FOR ME, i AM TORMENTED WITH AN EVERLASTING ITCH FOR
      THINGS REMOTE. i LOVE TO SAIL FORBIDDEN SEAS, AND LAND ON BARBAROUS
      COASTS. nOT IGNORING WHAT IS GOOD, i AM QUICK TO PERCEIVE A HORROR, AND
      COULD STILL BE SOCIAL WITH IT&MDASH;WOULD THEY LET ME&MDASH;SINCE IT IS
      BUT WELL TO BE ON FRIENDLY TERMS WITH ALL THE INMATES OF THE PLACE ONE
      LODGES IN.
    </P>
    <P>
      bY REASON OF THESE THINGS, THEN, THE WHALING VOYAGE WAS WELCOME; THE GREAT
      FLOOD-GATES OF THE WONDER-WORLD SWUNG OPEN, AND IN THE WILD CONCEITS THAT
      SWAYED ME TO MY PURPOSE, TWO AND TWO THERE FLOATED INTO MY INMOST SOUL,
      ENDLESS PROCESSIONS OF THE WHALE, AND, MID MOST OF THEM ALL, ONE GRAND
      HOODED PHANTOM, LIKE A SNOW HILL IN THE AIR.
    </P>
    <P>
      <A NAME="LINK2hch0002" ID="LINK2hch0002">
      <!--  h2 ANCHOR --> </A>
    </P>
    <DIV STYLE="HEIGHT: 4EM;">
      <BR /><BR /><BR /><BR />
    </DIV>
    <H2>
      chapter 2. tHE cARPET-bAG.
    </H2>
    <P>
      i STUFFED A SHIRT OR TWO INTO MY OLD CARPET-BAG, TUCKED IT UNDER MY ARM,
      AND STARTED FOR cAPE hORN AND THE pACIFIC. qUITTING THE GOOD CITY OF OLD
      mANHATTO, i DULY ARRIVED IN nEW bEDFORD. iT WAS A sATURDAY NIGHT IN
      dECEMBER. mUCH WAS i DISAPPOINTED UPON LEARNING THAT THE LITTLE PACKET FOR
      nANTUCKET HAD ALREADY SAILED, AND THAT NO WAY OF REACHING THAT PLACE WOULD
      OFFER, TILL THE FOLLOWING mONDAY.
    </P>
    <P>
      aS MOST YOUNG CANDIDATES FOR THE PAINS AND PENALTIES OF WHALING STOP AT
      THIS SAME nEW bEDFORD, THENCE TO EMBARK ON THEIR VOYAGE, IT MAY AS WELL BE
      RELATED THAT i, FOR ONE, HAD NO IDEA OF SO DOING. fOR MY MIND WAS MADE UP
      TO SAIL IN NO OTHER THAN A nANTUCKET CRAFT, BECAUSE THERE WAS A FINE,
      BOISTEROUS SOMETHING ABOUT EVERYTHING CONNECTED WITH THAT FAMOUS OLD
      ISLAND, WHICH AMAZINGLY PLEASED ME. bESIDES THOUGH nEW bEDFORD HAS OF LATE
      BEEN GRADUALLY MONOPOLISING THE BUSINESS OF WHALING, AND THOUGH IN THIS
      MATTER POOR OLD nANTUCKET IS NOW MUCH BEHIND HER, YET nANTUCKET WAS HER
      GREAT ORIGINAL&MDASH;THE tYRE OF THIS cARTHAGE;&MDASH;THE PLACE WHERE THE
      FIRST DEAD aMERICAN WHALE WAS STRANDED. wHERE ELSE BUT FROM nANTUCKET DID
      THOSE ABORIGINAL WHALEMEN, THE rED-mEN, FIRST SALLY OUT IN CANOES TO GIVE
      CHASE TO THE lEVIATHAN? aND WHERE BUT FROM nANTUCKET, TOO, DID THAT FIRST
      ADVENTUROUS LITTLE SLOOP PUT FORTH, PARTLY LADEN WITH IMPORTED
      COBBLESTONES&MDASH;SO GOES THE STORY&MDASH;TO THROW AT THE WHALES, IN
      ORDER TO DISCOVER WHEN THEY WERE NIGH ENOUGH TO RISK A HARPOON FROM THE
      BOWSPRIT?
    </P>
    <P>
      nOW HAVING A NIGHT, A DAY, AND STILL ANOTHER NIGHT FOLLOWING BEFORE ME IN
      nEW bEDFORD, ERE i COULD EMBARK FOR MY DESTINED PORT, IT BECAME A MATTER
      OF CONCERNMENT WHERE i WAS TO EAT AND SLEEP MEANWHILE. iT WAS A VERY
      DUBIOUS-LOOKING, NAY, A VERY DARK AND DISMAL NIGHT, BITINGLY COLD AND
      CHEERLESS. i KNEW NO ONE IN THE PLACE. wITH ANXIOUS GRAPNELS i HAD SOUNDED
      MY POCKET, AND ONLY BROUGHT UP A FEW PIECES OF SILVER,&MDASH;sO, WHEREVER
      YOU GO, iSHMAEL, SAID i TO MYSELF, AS i STOOD IN THE MIDDLE OF A DREARY
      STREET SHOULDERING MY BAG, AND COMPARING THE GLOOM TOWARDS THE NORTH WITH
      THE DARKNESS TOWARDS THE SOUTH&MDASH;WHEREVER IN YOUR WISDOM YOU MAY
      CONCLUDE TO LODGE FOR THE NIGHT, MY DEAR iSHMAEL, BE SURE TO INQUIRE THE
      PRICE, AND DON&RSQUO;T BE TOO PARTICULAR.
    </P>
    <P>
      wITH HALTING STEPS i PACED THE STREETS, AND PASSED THE SIGN OF &LDQUO;tHE
      cROSSED hARPOONS&RDQUO;&MDASH;BUT IT LOOKED TOO EXPENSIVE AND JOLLY THERE.
      fURTHER ON, FROM THE BRIGHT RED WINDOWS OF THE &LDQUO;sWORD-fISH iNN,&RDQUO; THERE
      CAME SUCH FERVENT RAYS, THAT IT SEEMED TO HAVE MELTED THE PACKED SNOW AND
      ICE FROM BEFORE THE HOUSE, FOR EVERYWHERE ELSE THE CONGEALED FROST LAY TEN
      INCHES THICK IN A HARD, ASPHALTIC PAVEMENT,&MDASH;RATHER WEARY FOR ME,
      WHEN i STRUCK MY FOOT AGAINST THE FLINTY PROJECTIONS, BECAUSE FROM HARD,
      REMORSELESS SERVICE THE SOLES OF MY BOOTS WERE IN A MOST MISERABLE PLIGHT.
      tOO EXPENSIVE AND JOLLY, AGAIN THOUGHT i, PAUSING ONE MOMENT TO WATCH THE
      BROAD GLARE IN THE STREET, AND HEAR THE SOUNDS OF THE TINKLING GLASSES
      WITHIN. bUT GO ON, iSHMAEL, SAID i AT LAST; DON&RSQUO;T YOU HEAR? GET AWAY FROM
      BEFORE THE DOOR; YOUR PATCHED BOOTS ARE STOPPING THE WAY. sO ON i WENT. i
      NOW BY INSTINCT FOLLOWED THE STREETS THAT TOOK ME WATERWARD, FOR THERE,
      DOUBTLESS, WERE THE CHEAPEST, IF NOT THE CHEERIEST INNS.
    </P>
    <P>
      sUCH DREARY STREETS! BLOCKS OF BLACKNESS, NOT HOUSES, ON EITHER HAND, AND
      HERE AND THERE A CANDLE, LIKE A CANDLE MOVING ABOUT IN A TOMB. aT THIS
      HOUR OF THE NIGHT, OF THE LAST DAY OF THE WEEK, THAT QUARTER OF THE TOWN
      PROVED ALL BUT DESERTED. bUT PRESENTLY i CAME TO A SMOKY LIGHT PROCEEDING
      FROM A LOW, WIDE BUILDING, THE DOOR OF WHICH STOOD INVITINGLY OPEN. iT HAD
      A CARELESS LOOK, AS IF IT WERE MEANT FOR THE USES OF THE PUBLIC; SO,
      ENTERING, THE FIRST THING i DID WAS TO STUMBLE OVER AN ASH-BOX IN THE
      PORCH. hA! THOUGHT i, HA, AS THE FLYING PARTICLES ALMOST CHOKED ME, ARE
      THESE ASHES FROM THAT DESTROYED CITY, gOMORRAH? bUT &LDQUO;tHE cROSSED
      hARPOONS,&RDQUO; AND &LDQUO;tHE sWORD-fISH?&RDQUO;&MDASH;THIS, THEN MUST NEEDS BE THE SIGN
      OF &LDQUO;tHE tRAP.&RDQUO; hOWEVER, i PICKED MYSELF UP AND HEARING A LOUD VOICE
      WITHIN, PUSHED ON AND OPENED A SECOND, INTERIOR DOOR.
    </P>
    <P>
      iT SEEMED THE GREAT bLACK pARLIAMENT SITTING IN tOPHET. a HUNDRED BLACK
      FACES TURNED ROUND IN THEIR ROWS TO PEER; AND BEYOND, A BLACK aNGEL OF
      dOOM WAS BEATING A BOOK IN A PULPIT. iT WAS A NEGRO CHURCH; AND THE
      PREACHER&RSQUO;S TEXT WAS ABOUT THE BLACKNESS OF DARKNESS, AND THE WEEPING AND
      WAILING AND TEETH-GNASHING THERE. hA, iSHMAEL, MUTTERED i, BACKING OUT,
      wRETCHED ENTERTAINMENT AT THE SIGN OF &LSQUO;tHE tRAP!&RSQUO; 
    </P>
    <P>
      mOVING ON, i AT LAST CAME TO A DIM SORT OF LIGHT NOT FAR FROM THE DOCKS,
      AND HEARD A FORLORN CREAKING IN THE AIR; AND LOOKING UP, SAW A SWINGING
      SIGN OVER THE DOOR WITH A WHITE PAINTING UPON IT, FAINTLY REPRESENTING A
      TALL STRAIGHT JET OF MISTY SPRAY, AND THESE WORDS UNDERNEATH&MDASH;&LDQUO;tHE
      sPOUTER iNN:&MDASH;pETER cOFFIN.&RDQUO;
     </P>
    <P>
      cOFFIN?&MDASH;sPOUTER?&MDASH;rATHER OMINOUS IN THAT PARTICULAR CONNEXION,
      THOUGHT i. bUT IT IS A COMMON NAME IN nANTUCKET, THEY SAY, AND i SUPPOSE
      THIS pETER HERE IS AN EMIGRANT FROM THERE. aS THE LIGHT LOOKED SO DIM, AND
      THE PLACE, FOR THE TIME, LOOKED QUIET ENOUGH, AND THE DILAPIDATED LITTLE
      WOODEN HOUSE ITSELF LOOKED AS IF IT MIGHT HAVE BEEN CARTED HERE FROM THE
      RUINS OF SOME BURNT DISTRICT, AND AS THE SWINGING SIGN HAD A
      POVERTY-STRICKEN SORT OF CREAK TO IT, i THOUGHT THAT HERE WAS THE VERY
      SPOT FOR CHEAP LODGINGS, AND THE BEST OF PEA COFFEE.
    </P>
    <P>
      iT WAS A QUEER SORT OF PLACE&MDASH;A GABLE-ENDED OLD HOUSE, ONE SIDE
      PALSIED AS IT WERE, AND LEANING OVER SADLY. iT STOOD ON A SHARP BLEAK
      CORNER, WHERE THAT TEMPESTUOUS WIND eUROCLYDON KEPT UP A WORSE HOWLING
      THAN EVER IT DID ABOUT POOR pAUL&RSQUO;S TOSSED CRAFT. eUROCLYDON, NEVERTHELESS,
      IS A MIGHTY PLEASANT ZEPHYR TO ANY ONE IN-DOORS, WITH HIS FEET ON THE HOB
      QUIETLY TOASTING FOR BED. &LDQUO;iN JUDGING OF THAT TEMPESTUOUS WIND CALLED
      eUROCLYDON,&RDQUO; SAYS AN OLD WRITER&MDASH;OF WHOSE WORKS i POSSESS THE ONLY
      COPY EXTANT&MDASH;&LDQUO;IT MAKETH A MARVELLOUS DIFFERENCE, WHETHER THOU LOOKEST
      OUT AT IT FROM A GLASS WINDOW WHERE THE FROST IS ALL ON THE OUTSIDE, OR
      WHETHER THOU OBSERVEST IT FROM THAT SASHLESS WINDOW, WHERE THE FROST IS ON
      BOTH SIDES, AND OF WHICH THE WIGHT dEATH IS THE ONLY GLAZIER.&RDQUO; tRUE
      ENOUGH, THOUGHT i, AS THIS PASSAGE OCCURRED TO MY MIND&MDASH;OLD
      BLACK-LETTER, THOU REASONEST WELL. yES, THESE EYES ARE WINDOWS, AND THIS
      BODY OF MINE IS THE HOUSE. wHAT A PITY THEY DIDN&RSQUO;T STOP UP THE CHINKS AND
      THE CRANNIES THOUGH, AND THRUST IN A LITTLE LINT HERE AND THERE. bUT IT&RSQUO;S
      TOO LATE TO MAKE ANY IMPROVEMENTS NOW. tHE UNIVERSE IS FINISHED; THE
      COPESTONE IS ON, AND THE CHIPS WERE CARTED OFF A MILLION YEARS AGO. pOOR
      lAZARUS THERE, CHATTERING HIS TEETH AGAINST THE CURBSTONE FOR HIS PILLOW,
      AND SHAKING OFF HIS TATTERS WITH HIS SHIVERINGS, HE MIGHT PLUG UP BOTH
      EARS WITH RAGS, AND PUT A CORN-COB INTO HIS MOUTH, AND YET THAT WOULD NOT
      KEEP OUT THE TEMPESTUOUS eUROCLYDON. eUROCLYDON! SAYS OLD dIVES, IN HIS
      RED SILKEN WRAPPER&MDASH;(HE HAD A REDDER ONE AFTERWARDS) POOH, POOH! wHAT
      A FINE FROSTY NIGHT; HOW oRION GLITTERS; WHAT NORTHERN LIGHTS! lET THEM
      TALK OF THEIR ORIENTAL SUMMER CLIMES OF EVERLASTING CONSERVATORIES; GIVE
      ME THE PRIVILEGE OF MAKING MY OWN SUMMER WITH MY OWN COALS.
    </P>
    <P>
      bUT WHAT THINKS lAZARUS? cAN HE WARM HIS BLUE HANDS BY HOLDING THEM UP TO
      THE GRAND NORTHERN LIGHTS? wOULD NOT lAZARUS RATHER BE IN sUMATRA THAN
      HERE? wOULD HE NOT FAR RATHER LAY HIM DOWN LENGTHWISE ALONG THE LINE OF
      THE EQUATOR; YEA, YE GODS! GO DOWN TO THE FIERY PIT ITSELF, IN ORDER TO
      KEEP OUT THIS FROST?
    </P>
    <P>
      nOW, THAT lAZARUS SHOULD LIE STRANDED THERE ON THE CURBSTONE BEFORE THE
      DOOR OF dIVES, THIS IS MORE WONDERFUL THAN THAT AN ICEBERG SHOULD BE
      MOORED TO ONE OF THE mOLUCCAS. yET dIVES HIMSELF, HE TOO LIVES LIKE A cZAR
      IN AN ICE PALACE MADE OF FROZEN SIGHS, AND BEING A PRESIDENT OF A
      TEMPERANCE SOCIETY, HE ONLY DRINKS THE TEPID TEARS OF ORPHANS.
    </P>
    <P>
      bUT NO MORE OF THIS BLUBBERING NOW, WE ARE GOING A-WHALING, AND THERE IS
      PLENTY OF THAT YET TO COME. lET US SCRAPE THE ICE FROM OUR FROSTED FEET,
      AND SEE WHAT SORT OF A PLACE THIS &LDQUO;sPOUTER&RDQUO; MAY BE.
    </P>
    <P>
      <A NAME="LINK2hch0003" ID="LINK2hch0003">
      <!--  h2 ANCHOR --> </A>
    </P>
    <DIV STYLE="HEIGHT: 4EM;">
      <BR /><BR /><BR /><BR />
    </DIV>
    <H2>
      chapter 3. tHE sPOUTER-iNN.
    </H2>
    <P>
      eNTERING THAT GABLE-ENDED sPOUTER-iNN, YOU FOUND YOURSELF IN A WIDE, LOW,
      STRAGGLING ENTRY WITH OLD-FASHIONED WAINSCOTS, REMINDING ONE OF THE
      BULWARKS OF SOME CONDEMNED OLD CRAFT. oN ONE SIDE HUNG A VERY LARGE
      OILPAINTING SO THOROUGHLY BESMOKED, AND EVERY WAY DEFACED, THAT IN THE
      UNEQUAL CROSSLIGHTS BY WHICH YOU VIEWED IT, IT WAS ONLY BY DILIGENT STUDY
      AND A SERIES OF SYSTEMATIC VISITS TO IT, AND CAREFUL INQUIRY OF THE
      NEIGHBORS, THAT YOU COULD ANY WAY ARRIVE AT AN UNDERSTANDING OF ITS
      PURPOSE. sUCH UNACCOUNTABLE MASSES OF SHADES AND SHADOWS, THAT AT FIRST
      YOU ALMOST THOUGHT SOME AMBITIOUS YOUNG ARTIST, IN THE TIME OF THE nEW
      eNGLAND HAGS, HAD ENDEAVORED TO DELINEATE CHAOS BEWITCHED. bUT BY DINT OF
      MUCH AND EARNEST CONTEMPLATION, AND OFT REPEATED PONDERINGS, AND
      ESPECIALLY BY THROWING OPEN THE LITTLE WINDOW TOWARDS THE BACK OF THE
      ENTRY, YOU AT LAST COME TO THE CONCLUSION THAT SUCH AN IDEA, HOWEVER WILD,
      MIGHT NOT BE ALTOGETHER UNWARRANTED.
    </P>
    <P>
      bUT WHAT MOST PUZZLED AND CONFOUNDED YOU WAS A LONG, LIMBER, PORTENTOUS,
      BLACK MASS OF SOMETHING HOVERING IN THE CENTRE OF THE PICTURE OVER THREE
      BLUE, DIM, PERPENDICULAR LINES FLOATING IN A NAMELESS YEAST. a BOGGY,
      SOGGY, SQUITCHY PICTURE TRULY, ENOUGH TO DRIVE A NERVOUS MAN DISTRACTED.
      yET WAS THERE A SORT OF INDEFINITE, HALF-ATTAINED, UNIMAGINABLE SUBLIMITY
      ABOUT IT THAT FAIRLY FROZE YOU TO IT, TILL YOU INVOLUNTARILY TOOK AN OATH
      WITH YOURSELF TO FIND OUT WHAT THAT MARVELLOUS PAINTING MEANT. eVER AND
      ANON A BRIGHT, BUT, ALAS, DECEPTIVE IDEA WOULD DART YOU THROUGH.&MDASH;iT&RSQUO;S
      THE bLACK sEA IN A MIDNIGHT GALE.&MDASH;iT&RSQUO;S THE UNNATURAL COMBAT OF THE
      FOUR PRIMAL ELEMENTS.&MDASH;iT&RSQUO;S A BLASTED HEATH.&MDASH;iT&RSQUO;S A hYPERBOREAN
      WINTER SCENE.&MDASH;iT&RSQUO;S THE BREAKING-UP OF THE ICEBOUND STREAM OF tIME.
      bUT AT LAST ALL THESE FANCIES YIELDED TO THAT ONE PORTENTOUS SOMETHING IN
      THE PICTURE&RSQUO;S MIDST. <I>tHAT</I> ONCE FOUND OUT, AND ALL THE REST WERE PLAIN. bUT
      STOP; DOES IT NOT BEAR A FAINT RESEMBLANCE TO A GIGANTIC FISH? EVEN THE
      GREAT LEVIATHAN HIMSELF?
    </P>
    <P>
      iN FACT, THE ARTIST&RSQUO;S DESIGN SEEMED THIS: A FINAL THEORY OF MY OWN, PARTLY
      BASED UPON THE AGGREGATED OPINIONS OF MANY AGED PERSONS WITH WHOM i
      CONVERSED UPON THE SUBJECT. tHE PICTURE REPRESENTS A cAPE-hORNER IN A
      GREAT HURRICANE; THE HALF-FOUNDERED SHIP WELTERING THERE WITH ITS THREE
      DISMANTLED MASTS ALONE VISIBLE; AND AN EXASPERATED WHALE, PURPOSING TO
      SPRING CLEAN OVER THE CRAFT, IS IN THE ENORMOUS ACT OF IMPALING HIMSELF
      UPON THE THREE MAST-HEADS.
    </P>
    <P>
      tHE OPPOSITE WALL OF THIS ENTRY WAS HUNG ALL OVER WITH A HEATHENISH ARRAY
      OF MONSTROUS CLUBS AND SPEARS. sOME WERE THICKLY SET WITH GLITTERING TEETH
      RESEMBLING IVORY SAWS; OTHERS WERE TUFTED WITH KNOTS OF HUMAN HAIR; AND
      ONE WAS SICKLE-SHAPED, WITH A VAST HANDLE SWEEPING ROUND LIKE THE SEGMENT
      MADE IN THE NEW-MOWN GRASS BY A LONG-ARMED MOWER. yOU SHUDDERED AS YOU
      GAZED, AND WONDERED WHAT MONSTROUS CANNIBAL AND SAVAGE COULD EVER HAVE
      GONE A DEATH-HARVESTING WITH SUCH A HACKING, HORRIFYING IMPLEMENT. mIXED
      WITH THESE WERE RUSTY OLD WHALING LANCES AND HARPOONS ALL BROKEN AND
      DEFORMED. sOME WERE STORIED WEAPONS. wITH THIS ONCE LONG LANCE, NOW WILDLY
      ELBOWED, FIFTY YEARS AGO DID nATHAN sWAIN KILL FIFTEEN WHALES BETWEEN A
      SUNRISE AND A SUNSET. aND THAT HARPOON&MDASH;SO LIKE A CORKSCREW NOW&MDASH;WAS
      FLUNG IN jAVAN SEAS, AND RUN AWAY WITH BY A WHALE, YEARS AFTERWARDS SLAIN
      OFF THE cAPE OF bLANCO. tHE ORIGINAL IRON ENTERED NIGH THE TAIL, AND, LIKE
      A RESTLESS NEEDLE SOJOURNING IN THE BODY OF A MAN, TRAVELLED FULL FORTY
      FEET, AND AT LAST WAS FOUND IMBEDDED IN THE HUMP.
    </P>
    <P>
      cROSSING THIS DUSKY ENTRY, AND ON THROUGH YON LOW-ARCHED WAY&MDASH;CUT
      THROUGH WHAT IN OLD TIMES MUST HAVE BEEN A GREAT CENTRAL CHIMNEY WITH
      FIREPLACES ALL ROUND&MDASH;YOU ENTER THE PUBLIC ROOM. a STILL DUSKIER
      PLACE IS THIS, WITH SUCH LOW PONDEROUS BEAMS ABOVE, AND SUCH OLD WRINKLED
      PLANKS BENEATH, THAT YOU WOULD ALMOST FANCY YOU TROD SOME OLD CRAFT&RSQUO;S
      COCKPITS, ESPECIALLY OF SUCH A HOWLING NIGHT, WHEN THIS CORNER-ANCHORED
      OLD ARK ROCKED SO FURIOUSLY. oN ONE SIDE STOOD A LONG, LOW, SHELF-LIKE
      TABLE COVERED WITH CRACKED GLASS CASES, FILLED WITH DUSTY RARITIES
      GATHERED FROM THIS WIDE WORLD&RSQUO;S REMOTEST NOOKS. pROJECTING FROM THE
      FURTHER ANGLE OF THE ROOM STANDS A DARK-LOOKING DEN&MDASH;THE BAR&MDASH;A
      RUDE ATTEMPT AT A RIGHT WHALE&RSQUO;S HEAD. bE THAT HOW IT MAY, THERE STANDS THE
      VAST ARCHED BONE OF THE WHALE&RSQUO;S JAW, SO WIDE, A COACH MIGHT ALMOST DRIVE
      BENEATH IT. wITHIN ARE SHABBY SHELVES, RANGED ROUND WITH OLD DECANTERS,
      BOTTLES, FLASKS; AND IN THOSE JAWS OF SWIFT DESTRUCTION, LIKE ANOTHER
      CURSED jONAH (BY WHICH NAME INDEED THEY CALLED HIM), BUSTLES A LITTLE
      WITHERED OLD MAN, WHO, FOR THEIR MONEY, DEARLY SELLS THE SAILORS DELIRIUMS
      AND DEATH.
    </P>
    <P>
      aBOMINABLE ARE THE TUMBLERS INTO WHICH HE POURS HIS POISON. tHOUGH TRUE
      CYLINDERS WITHOUT&MDASH;WITHIN, THE VILLANOUS GREEN GOGGLING GLASSES
      DECEITFULLY TAPERED DOWNWARDS TO A CHEATING BOTTOM. pARALLEL MERIDIANS
      RUDELY PECKED INTO THE GLASS, SURROUND THESE FOOTPADS&RSQUO; GOBLETS. fILL TO
      <I>THIS</I> MARK, AND YOUR CHARGE IS BUT A PENNY; TO <I>THIS</I> A PENNY MORE; AND SO ON
      TO THE FULL GLASS&MDASH;THE cAPE hORN MEASURE, WHICH YOU MAY GULP DOWN FOR
      A SHILLING.
    </P>
    <P>
      uPON ENTERING THE PLACE i FOUND A NUMBER OF YOUNG SEAMEN GATHERED ABOUT A
      TABLE, EXAMINING BY A DIM LIGHT DIVERS SPECIMENS OF <I>SKRIMSHANDER</I>. i SOUGHT
      THE LANDLORD, AND TELLING HIM i DESIRED TO BE ACCOMMODATED WITH A ROOM,
      RECEIVED FOR ANSWER THAT HIS HOUSE WAS FULL&MDASH;NOT A BED UNOCCUPIED.
      &LDQUO;bUT AVAST,&RDQUO; HE ADDED, TAPPING HIS FOREHEAD, &LDQUO;YOU HAINT NO OBJECTIONS TO
      SHARING A HARPOONEER&RSQUO;S BLANKET, HAVE YE? i S&RSQUO;POSE YOU ARE GOIN&RSQUO; A-WHALIN&RSQUO;,
      SO YOU&RSQUO;D BETTER GET USED TO THAT SORT OF THING.&RDQUO;
     </P>
    <P>
      i TOLD HIM THAT i NEVER LIKED TO SLEEP TWO IN A BED; THAT IF i SHOULD EVER
      DO SO, IT WOULD DEPEND UPON WHO THE HARPOONEER MIGHT BE, AND THAT IF HE
      (THE LANDLORD) REALLY HAD NO OTHER PLACE FOR ME, AND THE HARPOONEER WAS
      NOT DECIDEDLY OBJECTIONABLE, WHY RATHER THAN WANDER FURTHER ABOUT A
      STRANGE TOWN ON SO BITTER A NIGHT, i WOULD PUT UP WITH THE HALF OF ANY
      DECENT MAN&RSQUO;S BLANKET.
    </P>
    <P>
      &LDQUO;i THOUGHT SO. aLL RIGHT; TAKE A SEAT. sUPPER?&MDASH;YOU WANT SUPPER?
      sUPPER&RSQUO;LL BE READY DIRECTLY.&RDQUO;
     </P>
    <P>
      i SAT DOWN ON AN OLD WOODEN SETTLE, CARVED ALL OVER LIKE A BENCH ON THE
      bATTERY. aT ONE END A RUMINATING TAR WAS STILL FURTHER ADORNING IT WITH
      HIS JACK-KNIFE, STOOPING OVER AND DILIGENTLY WORKING AWAY AT THE SPACE
      BETWEEN HIS LEGS. hE WAS TRYING HIS HAND AT A SHIP UNDER FULL SAIL, BUT HE
      DIDN&RSQUO;T MAKE MUCH HEADWAY, i THOUGHT.
    </P>
    <P>
      aT LAST SOME FOUR OR FIVE OF US WERE SUMMONED TO OUR MEAL IN AN ADJOINING
      ROOM. iT WAS COLD AS iCELAND&MDASH;NO FIRE AT ALL&MDASH;THE LANDLORD SAID
      HE COULDN&RSQUO;T AFFORD IT. nOTHING BUT TWO DISMAL TALLOW CANDLES, EACH IN A
      WINDING SHEET. wE WERE FAIN TO BUTTON UP OUR MONKEY JACKETS, AND HOLD TO
      OUR LIPS CUPS OF SCALDING TEA WITH OUR HALF FROZEN FINGERS. bUT THE FARE
      WAS OF THE MOST SUBSTANTIAL KIND&MDASH;NOT ONLY MEAT AND POTATOES, BUT
      DUMPLINGS; GOOD HEAVENS! DUMPLINGS FOR SUPPER! oNE YOUNG FELLOW IN A GREEN
      BOX COAT, ADDRESSED HIMSELF TO THESE DUMPLINGS IN A MOST DIREFUL MANNER.
    </P>
    <P>
      &LDQUO;mY BOY,&RDQUO; SAID THE LANDLORD, &LDQUO;YOU&RSQUO;LL HAVE THE NIGHTMARE TO A DEAD
      SARTAINTY.&RDQUO;
     </P>
    <P>
      &LDQUO;lANDLORD,&RDQUO; i WHISPERED, &LDQUO;THAT AINT THE HARPOONEER IS IT?&RDQUO;
     </P>
    <P>
      &LDQUO;oH, NO,&RDQUO; SAID HE, LOOKING A SORT OF DIABOLICALLY FUNNY, &LDQUO;THE HARPOONEER
      IS A DARK COMPLEXIONED CHAP. hE NEVER EATS DUMPLINGS, HE DON&RSQUO;T&MDASH;HE
      EATS NOTHING BUT STEAKS, AND HE LIKES &RSQUO;EM RARE.&RDQUO;
     </P>
    <P>
      &LDQUO;tHE DEVIL HE DOES,&RDQUO; SAYS i. &LDQUO;wHERE IS THAT HARPOONEER? iS HE HERE?&RDQUO;
     </P>
    <P>
      &LDQUO;hE&RSQUO;LL BE HERE AFORE LONG,&RDQUO; WAS THE ANSWER.
    </P>
    <P>
      i COULD NOT HELP IT, BUT i BEGAN TO FEEL SUSPICIOUS OF THIS &LDQUO;DARK
      COMPLEXIONED&RDQUO; HARPOONEER. aT ANY RATE, i MADE UP MY MIND THAT IF IT SO
      TURNED OUT THAT WE SHOULD SLEEP TOGETHER, HE MUST UNDRESS AND GET INTO BED
      BEFORE i DID.
    </P>
    <P>
      sUPPER OVER, THE COMPANY WENT BACK TO THE BAR-ROOM, WHEN, KNOWING NOT WHAT
      ELSE TO DO WITH MYSELF, i RESOLVED TO SPEND THE REST OF THE EVENING AS A
      LOOKER ON.
    </P>
    <P>
      pRESENTLY A RIOTING NOISE WAS HEARD WITHOUT. sTARTING UP, THE LANDLORD
      CRIED, &LDQUO;tHAT&RSQUO;S THE gRAMPUS&RSQUO;S CREW. i SEED HER REPORTED IN THE OFFING THIS
      MORNING; A THREE YEARS&RSQUO; VOYAGE, AND A FULL SHIP. hURRAH, BOYS; NOW WE&RSQUO;LL
      HAVE THE LATEST NEWS FROM THE fEEGEES.&RDQUO;
     </P>
    <P>
      a TRAMPING OF SEA BOOTS WAS HEARD IN THE ENTRY; THE DOOR WAS FLUNG OPEN,
      AND IN ROLLED A WILD SET OF MARINERS ENOUGH. eNVELOPED IN THEIR SHAGGY
      WATCH COATS, AND WITH THEIR HEADS MUFFLED IN WOOLLEN COMFORTERS, ALL
      BEDARNED AND RAGGED, AND THEIR BEARDS STIFF WITH ICICLES, THEY SEEMED AN
      ERUPTION OF BEARS FROM lABRADOR. tHEY HAD JUST LANDED FROM THEIR BOAT, AND
      THIS WAS THE FIRST HOUSE THEY ENTERED. nO WONDER, THEN, THAT THEY MADE A
      STRAIGHT WAKE FOR THE WHALE&RSQUO;S MOUTH&MDASH;THE BAR&MDASH;WHEN THE WRINKLED
      LITTLE OLD jONAH, THERE OFFICIATING, SOON POURED THEM OUT BRIMMERS ALL
      ROUND. oNE COMPLAINED OF A BAD COLD IN HIS HEAD, UPON WHICH jONAH MIXED
      HIM A PITCH-LIKE POTION OF GIN AND MOLASSES, WHICH HE SWORE WAS A
      SOVEREIGN CURE FOR ALL COLDS AND CATARRHS WHATSOEVER, NEVER MIND OF HOW
      LONG STANDING, OR WHETHER CAUGHT OFF THE COAST OF lABRADOR, OR ON THE
      WEATHER SIDE OF AN ICE-ISLAND.
    </P>
    <P>
      tHE LIQUOR SOON MOUNTED INTO THEIR HEADS, AS IT GENERALLY DOES EVEN WITH
      THE ARRANTEST TOPERS NEWLY LANDED FROM SEA, AND THEY BEGAN CAPERING ABOUT
      MOST OBSTREPEROUSLY.
    </P>
    <P>
      i OBSERVED, HOWEVER, THAT ONE OF THEM HELD SOMEWHAT ALOOF, AND THOUGH HE
      SEEMED DESIROUS NOT TO SPOIL THE HILARITY OF HIS SHIPMATES BY HIS OWN
      SOBER FACE, YET UPON THE WHOLE HE REFRAINED FROM MAKING AS MUCH NOISE AS
      THE REST. tHIS MAN INTERESTED ME AT ONCE; AND SINCE THE SEA-GODS HAD
      ORDAINED THAT HE SHOULD SOON BECOME MY SHIPMATE (THOUGH BUT A
      SLEEPING-PARTNER ONE, SO FAR AS THIS NARRATIVE IS CONCERNED), i WILL HERE
      VENTURE UPON A LITTLE DESCRIPTION OF HIM. hE STOOD FULL SIX FEET IN
      HEIGHT, WITH NOBLE SHOULDERS, AND A CHEST LIKE A COFFER-DAM. i HAVE SELDOM
      SEEN SUCH BRAWN IN A MAN. hIS FACE WAS DEEPLY BROWN AND BURNT, MAKING HIS
      WHITE TEETH DAZZLING BY THE CONTRAST; WHILE IN THE DEEP SHADOWS OF HIS
      EYES FLOATED SOME REMINISCENCES THAT DID NOT SEEM TO GIVE HIM MUCH JOY.
      hIS VOICE AT ONCE ANNOUNCED THAT HE WAS A sOUTHERNER, AND FROM HIS FINE
      STATURE, i THOUGHT HE MUST BE ONE OF THOSE TALL MOUNTAINEERS FROM THE
      aLLEGHANIAN rIDGE IN vIRGINIA. wHEN THE REVELRY OF HIS COMPANIONS HAD
      MOUNTED TO ITS HEIGHT, THIS MAN SLIPPED AWAY UNOBSERVED, AND i SAW NO MORE
      OF HIM TILL HE BECAME MY COMRADE ON THE SEA. iN A FEW MINUTES, HOWEVER, HE
      WAS MISSED BY HIS SHIPMATES, AND BEING, IT SEEMS, FOR SOME REASON A HUGE
      FAVOURITE WITH THEM, THEY RAISED A CRY OF &LDQUO;bULKINGTON! bULKINGTON! WHERE&RSQUO;S
      bULKINGTON?&RDQUO; AND DARTED OUT OF THE HOUSE IN PURSUIT OF HIM.
    </P>
    <P>
      iT WAS NOW ABOUT NINE O&RSQUO;CLOCK, AND THE ROOM SEEMING ALMOST SUPERNATURALLY
      QUIET AFTER THESE ORGIES, i BEGAN TO CONGRATULATE MYSELF UPON A LITTLE
      PLAN THAT HAD OCCURRED TO ME JUST PREVIOUS TO THE ENTRANCE OF THE SEAMEN.
    </P>
    <P>
      nO MAN PREFERS TO SLEEP TWO IN A BED. iN FACT, YOU WOULD A GOOD DEAL
      RATHER NOT SLEEP WITH YOUR OWN BROTHER. i DON&RSQUO;T KNOW HOW IT IS, BUT PEOPLE
      LIKE TO BE PRIVATE WHEN THEY ARE SLEEPING. aND WHEN IT COMES TO SLEEPING
      WITH AN UNKNOWN STRANGER, IN A STRANGE INN, IN A STRANGE TOWN, AND THAT
      STRANGER A HARPOONEER, THEN YOUR OBJECTIONS INDEFINITELY MULTIPLY. nOR WAS
      THERE ANY EARTHLY REASON WHY i AS A SAILOR SHOULD SLEEP TWO IN A BED, MORE
      THAN ANYBODY ELSE; FOR SAILORS NO MORE SLEEP TWO IN A BED AT SEA, THAN
      BACHELOR kINGS DO ASHORE. tO BE SURE THEY ALL SLEEP TOGETHER IN ONE
      APARTMENT, BUT YOU HAVE YOUR OWN HAMMOCK, AND COVER YOURSELF WITH YOUR OWN
      BLANKET, AND SLEEP IN YOUR OWN SKIN.
    </P>
    <P>
      tHE MORE i PONDERED OVER THIS HARPOONEER, THE MORE i ABOMINATED THE
      THOUGHT OF SLEEPING WITH HIM. iT WAS FAIR TO PRESUME THAT BEING A
      HARPOONEER, HIS LINEN OR WOOLLEN, AS THE CASE MIGHT BE, WOULD NOT BE OF
      THE TIDIEST, CERTAINLY NONE OF THE FINEST. i BEGAN TO TWITCH ALL OVER.
      bESIDES, IT WAS GETTING LATE, AND MY DECENT HARPOONEER OUGHT TO BE HOME
      AND GOING BEDWARDS. sUPPOSE NOW, HE SHOULD TUMBLE IN UPON ME AT MIDNIGHT&MDASH;HOW
      COULD i TELL FROM WHAT VILE HOLE HE HAD BEEN COMING?
    </P>
    <P>
      &LDQUO;lANDLORD! i&RSQUO;VE CHANGED MY MIND ABOUT THAT HARPOONEER.&MDASH;i SHAN&RSQUO;T
      SLEEP WITH HIM. i&RSQUO;LL TRY THE BENCH HERE.&RDQUO;
     </P>
    <P>
      &LDQUO;jUST AS YOU PLEASE; i&RSQUO;M SORRY i CAN&RSQUO;T SPARE YE A TABLECLOTH FOR A
      MATTRESS, AND IT&RSQUO;S A PLAGUY ROUGH BOARD HERE&RDQUO;&MDASH;FEELING OF THE KNOTS
      AND NOTCHES. &LDQUO;bUT WAIT A BIT, sKRIMSHANDER; i&RSQUO;VE GOT A CARPENTER&RSQUO;S PLANE
      THERE IN THE BAR&MDASH;WAIT, i SAY, AND i&RSQUO;LL MAKE YE SNUG ENOUGH.&RDQUO; sO
      SAYING HE PROCURED THE PLANE; AND WITH HIS OLD SILK HANDKERCHIEF FIRST
      DUSTING THE BENCH, VIGOROUSLY SET TO PLANING AWAY AT MY BED, THE WHILE
      GRINNING LIKE AN APE. tHE SHAVINGS FLEW RIGHT AND LEFT; TILL AT LAST THE
      PLANE-IRON CAME BUMP AGAINST AN INDESTRUCTIBLE KNOT. tHE LANDLORD WAS NEAR
      SPRAINING HIS WRIST, AND i TOLD HIM FOR HEAVEN&RSQUO;S SAKE TO QUIT&MDASH;THE
      BED WAS SOFT ENOUGH TO SUIT ME, AND i DID NOT KNOW HOW ALL THE PLANING IN
      THE WORLD COULD MAKE EIDER DOWN OF A PINE PLANK. sO GATHERING UP THE
      SHAVINGS WITH ANOTHER GRIN, AND THROWING THEM INTO THE GREAT STOVE IN THE
      MIDDLE OF THE ROOM, HE WENT ABOUT HIS BUSINESS, AND LEFT ME IN A BROWN
      STUDY.
    </P>
    <P>
      i NOW TOOK THE MEASURE OF THE BENCH, AND FOUND THAT IT WAS A FOOT TOO
      SHORT; BUT THAT COULD BE MENDED WITH A CHAIR. bUT IT WAS A FOOT TOO
      NARROW, AND THE OTHER BENCH IN THE ROOM WAS ABOUT FOUR INCHES HIGHER THAN
      THE PLANED ONE&MDASH;SO THERE WAS NO YOKING THEM. i THEN PLACED THE FIRST
      BENCH LENGTHWISE ALONG THE ONLY CLEAR SPACE AGAINST THE WALL, LEAVING A
      LITTLE INTERVAL BETWEEN, FOR MY BACK TO SETTLE DOWN IN. bUT i SOON FOUND
      THAT THERE CAME SUCH A DRAUGHT OF COLD AIR OVER ME FROM UNDER THE SILL OF
      THE WINDOW, THAT THIS PLAN WOULD NEVER DO AT ALL, ESPECIALLY AS ANOTHER
      CURRENT FROM THE RICKETY DOOR MET THE ONE FROM THE WINDOW, AND BOTH
      TOGETHER FORMED A SERIES OF SMALL WHIRLWINDS IN THE IMMEDIATE VICINITY OF
      THE SPOT WHERE i HAD THOUGHT TO SPEND THE NIGHT.
    </P>
    <P>
      tHE DEVIL FETCH THAT HARPOONEER, THOUGHT i, BUT STOP, COULDN&RSQUO;T i STEAL A
      MARCH ON HIM&MDASH;BOLT HIS DOOR INSIDE, AND JUMP INTO HIS BED, NOT TO BE
      WAKENED BY THE MOST VIOLENT KNOCKINGS? iT SEEMED NO BAD IDEA; BUT UPON
      SECOND THOUGHTS i DISMISSED IT. fOR WHO COULD TELL BUT WHAT THE NEXT
      MORNING, SO SOON AS i POPPED OUT OF THE ROOM, THE HARPOONEER MIGHT BE
      STANDING IN THE ENTRY, ALL READY TO KNOCK ME DOWN!
    </P>
    <P>
      sTILL, LOOKING ROUND ME AGAIN, AND SEEING NO POSSIBLE CHANCE OF SPENDING A
      SUFFERABLE NIGHT UNLESS IN SOME OTHER PERSON&RSQUO;S BED, i BEGAN TO THINK THAT
      AFTER ALL i MIGHT BE CHERISHING UNWARRANTABLE PREJUDICES AGAINST THIS
      UNKNOWN HARPOONEER. tHINKS i, i&RSQUO;LL WAIT AWHILE; HE MUST BE DROPPING IN
      BEFORE LONG. i&RSQUO;LL HAVE A GOOD LOOK AT HIM THEN, AND PERHAPS WE MAY BECOME
      JOLLY GOOD BEDFELLOWS AFTER ALL&MDASH;THERE&RSQUO;S NO TELLING.
    </P>
    <P>
      bUT THOUGH THE OTHER BOARDERS KEPT COMING IN BY ONES, TWOS, AND THREES,
      AND GOING TO BED, YET NO SIGN OF MY HARPOONEER.
    </P>
    <P>
      &LDQUO;lANDLORD!&RDQUO; SAID i, &LDQUO;WHAT SORT OF A CHAP IS HE&MDASH;DOES HE ALWAYS KEEP
      SUCH LATE HOURS?&RDQUO; iT WAS NOW HARD UPON TWELVE O&RSQUO;CLOCK.
    </P>
    <P>
      tHE LANDLORD CHUCKLED AGAIN WITH HIS LEAN CHUCKLE, AND SEEMED TO BE
      MIGHTILY TICKLED AT SOMETHING BEYOND MY COMPREHENSION. &LDQUO;nO,&RDQUO; HE ANSWERED,
      &LDQUO;GENERALLY HE&RSQUO;S AN EARLY BIRD&MDASH;AIRLEY TO BED AND AIRLEY TO RISE&MDASH;YES,
      HE&RSQUO;S THE BIRD WHAT CATCHES THE WORM. bUT TO-NIGHT HE WENT OUT A PEDDLING,
      YOU SEE, AND i DON&RSQUO;T SEE WHAT ON AIRTH KEEPS HIM SO LATE, UNLESS, MAY BE,
      HE CAN&RSQUO;T SELL HIS HEAD.&RDQUO;
     </P>
    <P>
      &LDQUO;cAN&RSQUO;T SELL HIS HEAD?&MDASH;wHAT SORT OF A BAMBOOZINGLY STORY IS THIS YOU
      ARE TELLING ME?&RDQUO; GETTING INTO A TOWERING RAGE. &LDQUO;dO YOU PRETEND TO SAY,
      LANDLORD, THAT THIS HARPOONEER IS ACTUALLY ENGAGED THIS BLESSED sATURDAY
      NIGHT, OR RATHER sUNDAY MORNING, IN PEDDLING HIS HEAD AROUND THIS TOWN?&RDQUO;
     </P>
    <P>
      &LDQUO;tHAT&RSQUO;S PRECISELY IT,&RDQUO; SAID THE LANDLORD, &LDQUO;AND i TOLD HIM HE COULDN&RSQUO;T SELL
      IT HERE, THE MARKET&RSQUO;S OVERSTOCKED.&RDQUO;
     </P>
    <P>
      &LDQUO;wITH WHAT?&RDQUO; SHOUTED i.
    </P>
    <P>
      &LDQUO;wITH HEADS TO BE SURE; AIN&RSQUO;T THERE TOO MANY HEADS IN THE WORLD?&RDQUO;
     </P>
    <P>
      &LDQUO;i TELL YOU WHAT IT IS, LANDLORD,&RDQUO; SAID i QUITE CALMLY, &LDQUO;YOU&RSQUO;D BETTER STOP
      SPINNING THAT YARN TO ME&MDASH;i&RSQUO;M NOT GREEN.&RDQUO;
     </P>
    <P>
      &LDQUO;mAY BE NOT,&RDQUO; TAKING OUT A STICK AND WHITTLING A TOOTHPICK, &LDQUO;BUT i RAYTHER
      GUESS YOU&RSQUO;LL BE DONE <I>BROWN</I> IF THAT ERE HARPOONEER HEARS YOU A SLANDERIN&RSQUO; 
      HIS HEAD.&RDQUO;
     </P>
    <P>
      &LDQUO;i&RSQUO;LL BREAK IT FOR HIM,&RDQUO; SAID i, NOW FLYING INTO A PASSION AGAIN AT THIS
      UNACCOUNTABLE FARRAGO OF THE LANDLORD&RSQUO;S.
    </P>
    <P>
      &LDQUO;iT&RSQUO;S BROKE A&RSQUO;READY,&RDQUO; SAID HE.
    </P>
    <P>
      &LDQUO;bROKE,&RDQUO; SAID i&MDASH;&LDQUO;<I>BROKE</I>, DO YOU MEAN?&RDQUO;
     </P>
    <P>
      &LDQUO;sARTAIN, AND THAT&RSQUO;S THE VERY REASON HE CAN&RSQUO;T SELL IT, i GUESS.&RDQUO;
     </P>
    <P>
      &LDQUO;lANDLORD,&RDQUO; SAID i, GOING UP TO HIM AS COOL AS mT. hECLA IN A SNOW-STORM&MDASH;&LDQUO;LANDLORD,
      STOP WHITTLING. yOU AND i MUST UNDERSTAND ONE ANOTHER, AND THAT TOO
      WITHOUT DELAY. i COME TO YOUR HOUSE AND WANT A BED; YOU TELL ME YOU CAN
      ONLY GIVE ME HALF A ONE; THAT THE OTHER HALF BELONGS TO A CERTAIN
      HARPOONEER. aND ABOUT THIS HARPOONEER, WHOM i HAVE NOT YET SEEN, YOU
      PERSIST IN TELLING ME THE MOST MYSTIFYING AND EXASPERATING STORIES TENDING
      TO BEGET IN ME AN UNCOMFORTABLE FEELING TOWARDS THE MAN WHOM YOU DESIGN
      FOR MY BEDFELLOW&MDASH;A SORT OF CONNEXION, LANDLORD, WHICH IS AN INTIMATE
      AND CONFIDENTIAL ONE IN THE HIGHEST DEGREE. i NOW DEMAND OF YOU TO SPEAK
      OUT AND TELL ME WHO AND WHAT THIS HARPOONEER IS, AND WHETHER i SHALL BE IN
      ALL RESPECTS SAFE TO SPEND THE NIGHT WITH HIM. aND IN THE FIRST PLACE, YOU
      WILL BE SO GOOD AS TO UNSAY THAT STORY ABOUT SELLING HIS HEAD, WHICH IF
      TRUE i TAKE TO BE GOOD EVIDENCE THAT THIS HARPOONEER IS STARK MAD, AND
      i&RSQUO;VE NO IDEA OF SLEEPING WITH A MADMAN; AND YOU, SIR, <I>YOU</I> i MEAN,
      LANDLORD, <I>YOU</I>, SIR, BY TRYING TO INDUCE ME TO DO SO KNOWINGLY, WOULD
      THEREBY RENDER YOURSELF LIABLE TO A CRIMINAL PROSECUTION.&RDQUO;
     </P>
    <P>
      &LDQUO;wALL,&RDQUO; SAID THE LANDLORD, FETCHING A LONG BREATH, &LDQUO;THAT&RSQUO;S A PURTY LONG
      SARMON FOR A CHAP THAT RIPS A LITTLE NOW AND THEN. bUT BE EASY, BE EASY,
      THIS HERE HARPOONEER i HAVE BEEN TELLIN&RSQUO; YOU OF HAS JUST ARRIVED FROM THE
      SOUTH SEAS, WHERE HE BOUGHT UP A LOT OF &RSQUO;BALMED nEW zEALAND HEADS (GREAT
      CURIOS, YOU KNOW), AND HE&RSQUO;S SOLD ALL ON &RSQUO;EM BUT ONE, AND THAT ONE HE&RSQUO;S
      TRYING TO SELL TO-NIGHT, CAUSE TO-MORROW&RSQUO;S sUNDAY, AND IT WOULD NOT DO TO
      BE SELLIN&RSQUO; HUMAN HEADS ABOUT THE STREETS WHEN FOLKS IS GOIN&RSQUO; TO CHURCHES.
      hE WANTED TO, LAST sUNDAY, BUT i STOPPED HIM JUST AS HE WAS GOIN&RSQUO; OUT OF
      THE DOOR WITH FOUR HEADS STRUNG ON A STRING, FOR ALL THE AIRTH LIKE A
      STRING OF INIONS.&RDQUO;
     </P>
    <P>
      tHIS ACCOUNT CLEARED UP THE OTHERWISE UNACCOUNTABLE MYSTERY, AND SHOWED
      THAT THE LANDLORD, AFTER ALL, HAD HAD NO IDEA OF FOOLING ME&MDASH;BUT AT
      THE SAME TIME WHAT COULD i THINK OF A HARPOONEER WHO STAYED OUT OF A
      sATURDAY NIGHT CLEAN INTO THE HOLY sABBATH, ENGAGED IN SUCH A CANNIBAL
      BUSINESS AS SELLING THE HEADS OF DEAD IDOLATORS?
    </P>
    <P>
      &LDQUO;dEPEND UPON IT, LANDLORD, THAT HARPOONEER IS A DANGEROUS MAN.&RDQUO;
     </P>
    <P>
      &LDQUO;hE PAYS REG&RSQUO;LAR,&RDQUO; WAS THE REJOINDER. &LDQUO;bUT COME, IT&RSQUO;S GETTING DREADFUL
      LATE, YOU HAD BETTER BE TURNING FLUKES&MDASH;IT&RSQUO;S A NICE BED; sAL AND ME
      SLEPT IN THAT ERE BED THE NIGHT WE WERE SPLICED. tHERE&RSQUO;S PLENTY OF ROOM
      FOR TWO TO KICK ABOUT IN THAT BED; IT&RSQUO;S AN ALMIGHTY BIG BED THAT. wHY,
      AFORE WE GIVE IT UP, sAL USED TO PUT OUR sAM AND LITTLE jOHNNY IN THE FOOT
      OF IT. bUT i GOT A DREAMING AND SPRAWLING ABOUT ONE NIGHT, AND SOMEHOW,
      sAM GOT PITCHED ON THE FLOOR, AND CAME NEAR BREAKING HIS ARM. aRTER THAT,
      sAL SAID IT WOULDN&RSQUO;T DO. cOME ALONG HERE, i&RSQUO;LL GIVE YE A GLIM IN A JIFFY;&RDQUO;
       AND SO SAYING HE LIGHTED A CANDLE AND HELD IT TOWARDS ME, OFFERING TO LEAD
      THE WAY. bUT i STOOD IRRESOLUTE; WHEN LOOKING AT A CLOCK IN THE CORNER, HE
      EXCLAIMED &LDQUO;i VUM IT&RSQUO;S sUNDAY&MDASH;YOU WON&RSQUO;T SEE THAT HARPOONEER TO-NIGHT;
      HE&RSQUO;S COME TO ANCHOR SOMEWHERE&MDASH;COME ALONG THEN; <I>DO</I> COME; <I>WON&RSQUO;T</I> YE
      COME?&RDQUO;
     </P>
    <P>
      i CONSIDERED THE MATTER A MOMENT, AND THEN UP STAIRS WE WENT, AND i WAS
      USHERED INTO A SMALL ROOM, COLD AS A CLAM, AND FURNISHED, SURE ENOUGH,
      WITH A PRODIGIOUS BED, ALMOST BIG ENOUGH INDEED FOR ANY FOUR HARPOONEERS
      TO SLEEP ABREAST.
    </P>
    <P>
      &LDQUO;tHERE,&RDQUO; SAID THE LANDLORD, PLACING THE CANDLE ON A CRAZY OLD SEA CHEST
      THAT DID DOUBLE DUTY AS A WASH-STAND AND CENTRE TABLE; &LDQUO;THERE, MAKE
      YOURSELF COMFORTABLE NOW, AND GOOD NIGHT TO YE.&RDQUO; i TURNED ROUND FROM
      EYEING THE BED, BUT HE HAD DISAPPEARED.
    </P>
    <P>
      fOLDING BACK THE COUNTERPANE, i STOOPED OVER THE BED. tHOUGH NONE OF THE
      MOST ELEGANT, IT YET STOOD THE SCRUTINY TOLERABLY WELL. i THEN GLANCED
      ROUND THE ROOM; AND BESIDES THE BEDSTEAD AND CENTRE TABLE, COULD SEE NO
      OTHER FURNITURE BELONGING TO THE PLACE, BUT A RUDE SHELF, THE FOUR WALLS,
      AND A PAPERED FIREBOARD REPRESENTING A MAN STRIKING A WHALE. oF THINGS NOT
      PROPERLY BELONGING TO THE ROOM, THERE WAS A HAMMOCK LASHED UP, AND THROWN
      UPON THE FLOOR IN ONE CORNER; ALSO A LARGE SEAMAN&RSQUO;S BAG, CONTAINING THE
      HARPOONEER&RSQUO;S WARDROBE, NO DOUBT IN LIEU OF A LAND TRUNK. lIKEWISE, THERE
      WAS A PARCEL OF OUTLANDISH BONE FISH HOOKS ON THE SHELF OVER THE
      FIRE-PLACE, AND A TALL HARPOON STANDING AT THE HEAD OF THE BED.
    </P>
    <P>
      bUT WHAT IS THIS ON THE CHEST? i TOOK IT UP, AND HELD IT CLOSE TO THE
      LIGHT, AND FELT IT, AND SMELT IT, AND TRIED EVERY WAY POSSIBLE TO ARRIVE
      AT SOME SATISFACTORY CONCLUSION CONCERNING IT. i CAN COMPARE IT TO NOTHING
      BUT A LARGE DOOR MAT, ORNAMENTED AT THE EDGES WITH LITTLE TINKLING TAGS
      SOMETHING LIKE THE STAINED PORCUPINE QUILLS ROUND AN iNDIAN MOCCASIN.
      tHERE WAS A HOLE OR SLIT IN THE MIDDLE OF THIS MAT, AS YOU SEE THE SAME IN
      sOUTH aMERICAN PONCHOS. bUT COULD IT BE POSSIBLE THAT ANY SOBER HARPOONEER
      WOULD GET INTO A DOOR MAT, AND PARADE THE STREETS OF ANY cHRISTIAN TOWN IN
      THAT SORT OF GUISE? i PUT IT ON, TO TRY IT, AND IT WEIGHED ME DOWN LIKE A
      HAMPER, BEING UNCOMMONLY SHAGGY AND THICK, AND i THOUGHT A LITTLE DAMP, AS
      THOUGH THIS MYSTERIOUS HARPOONEER HAD BEEN WEARING IT OF A RAINY DAY. i
      WENT UP IN IT TO A BIT OF GLASS STUCK AGAINST THE WALL, AND i NEVER SAW
      SUCH A SIGHT IN MY LIFE. i TORE MYSELF OUT OF IT IN SUCH A HURRY THAT i
      GAVE MYSELF A KINK IN THE NECK.
    </P>
    <P>
      i SAT DOWN ON THE SIDE OF THE BED, AND COMMENCED THINKING ABOUT THIS
      HEAD-PEDDLING HARPOONEER, AND HIS DOOR MAT. aFTER THINKING SOME TIME ON
      THE BED-SIDE, i GOT UP AND TOOK OFF MY MONKEY JACKET, AND THEN STOOD IN
      THE MIDDLE OF THE ROOM THINKING. i THEN TOOK OFF MY COAT, AND THOUGHT A
      LITTLE MORE IN MY SHIRT SLEEVES. bUT BEGINNING TO FEEL VERY COLD NOW, HALF
      UNDRESSED AS i WAS, AND REMEMBERING WHAT THE LANDLORD SAID ABOUT THE
      HARPOONEER&RSQUO;S NOT COMING HOME AT ALL THAT NIGHT, IT BEING SO VERY LATE, i
      MADE NO MORE ADO, BUT JUMPED OUT OF MY PANTALOONS AND BOOTS, AND THEN
      BLOWING OUT THE LIGHT TUMBLED INTO BED, AND COMMENDED MYSELF TO THE CARE
      OF HEAVEN.
    </P>
    <P>
      wHETHER THAT MATTRESS WAS STUFFED WITH CORN-COBS OR BROKEN CROCKERY, THERE
      IS NO TELLING, BUT i ROLLED ABOUT A GOOD DEAL, AND COULD NOT SLEEP FOR A
      LONG TIME. aT LAST i SLID OFF INTO A LIGHT DOZE, AND HAD PRETTY NEARLY
      MADE A GOOD OFFING TOWARDS THE LAND OF nOD, WHEN i HEARD A HEAVY FOOTFALL
      IN THE PASSAGE, AND SAW A GLIMMER OF LIGHT COME INTO THE ROOM FROM UNDER
      THE DOOR.
    </P>
    <P>
      lORD SAVE ME, THINKS i, THAT MUST BE THE HARPOONEER, THE INFERNAL
      HEAD-PEDDLER. bUT i LAY PERFECTLY STILL, AND RESOLVED NOT TO SAY A WORD
      TILL SPOKEN TO. hOLDING A LIGHT IN ONE HAND, AND THAT IDENTICAL nEW
      zEALAND HEAD IN THE OTHER, THE STRANGER ENTERED THE ROOM, AND WITHOUT
      LOOKING TOWARDS THE BED, PLACED HIS CANDLE A GOOD WAY OFF FROM ME ON THE
      FLOOR IN ONE CORNER, AND THEN BEGAN WORKING AWAY AT THE KNOTTED CORDS OF
      THE LARGE BAG i BEFORE SPOKE OF AS BEING IN THE ROOM. i WAS ALL EAGERNESS
      TO SEE HIS FACE, BUT HE KEPT IT AVERTED FOR SOME TIME WHILE EMPLOYED IN
      UNLACING THE BAG&RSQUO;S MOUTH. tHIS ACCOMPLISHED, HOWEVER, HE TURNED ROUND&MDASH;WHEN,
      GOOD HEAVENS! WHAT A SIGHT! sUCH A FACE! iT WAS OF A DARK, PURPLISH,
      YELLOW COLOUR, HERE AND THERE STUCK OVER WITH LARGE BLACKISH LOOKING
      SQUARES. yES, IT&RSQUO;S JUST AS i THOUGHT, HE&RSQUO;S A TERRIBLE BEDFELLOW; HE&RSQUO;S BEEN
      IN A FIGHT, GOT DREADFULLY CUT, AND HERE HE IS, JUST FROM THE SURGEON. bUT
      AT THAT MOMENT HE CHANCED TO TURN HIS FACE SO TOWARDS THE LIGHT, THAT i
      PLAINLY SAW THEY COULD NOT BE STICKING-PLASTERS AT ALL, THOSE BLACK
      SQUARES ON HIS CHEEKS. tHEY WERE STAINS OF SOME SORT OR OTHER. aT FIRST i
      KNEW NOT WHAT TO MAKE OF THIS; BUT SOON AN INKLING OF THE TRUTH OCCURRED
      TO ME. i REMEMBERED A STORY OF A WHITE MAN&MDASH;A WHALEMAN TOO&MDASH;WHO,
      FALLING AMONG THE CANNIBALS, HAD BEEN TATTOOED BY THEM. i CONCLUDED THAT
      THIS HARPOONEER, IN THE COURSE OF HIS DISTANT VOYAGES, MUST HAVE MET WITH
      A SIMILAR ADVENTURE. aND WHAT IS IT, THOUGHT i, AFTER ALL! iT&RSQUO;S ONLY HIS
      OUTSIDE; A MAN CAN BE HONEST IN ANY SORT OF SKIN. bUT THEN, WHAT TO MAKE
      OF HIS UNEARTHLY COMPLEXION, THAT PART OF IT, i MEAN, LYING ROUND ABOUT,
      AND COMPLETELY INDEPENDENT OF THE SQUARES OF TATTOOING. tO BE SURE, IT
      MIGHT BE NOTHING BUT A GOOD COAT OF TROPICAL TANNING; BUT i NEVER HEARD OF
      A HOT SUN&RSQUO;S TANNING A WHITE MAN INTO A PURPLISH YELLOW ONE. hOWEVER, i HAD
      NEVER BEEN IN THE sOUTH sEAS; AND PERHAPS THE SUN THERE PRODUCED THESE
      EXTRAORDINARY EFFECTS UPON THE SKIN. nOW, WHILE ALL THESE IDEAS WERE
      PASSING THROUGH ME LIKE LIGHTNING, THIS HARPOONEER NEVER NOTICED ME AT
      ALL. bUT, AFTER SOME DIFFICULTY HAVING OPENED HIS BAG, HE COMMENCED
      FUMBLING IN IT, AND PRESENTLY PULLED OUT A SORT OF TOMAHAWK, AND A
      SEAL-SKIN WALLET WITH THE HAIR ON. pLACING THESE ON THE OLD CHEST IN THE
      MIDDLE OF THE ROOM, HE THEN TOOK THE nEW zEALAND HEAD&MDASH;A GHASTLY
      THING ENOUGH&MDASH;AND CRAMMED IT DOWN INTO THE BAG. hE NOW TOOK OFF HIS
      HAT&MDASH;A NEW BEAVER HAT&MDASH;WHEN i CAME NIGH SINGING OUT WITH FRESH
      SURPRISE. tHERE WAS NO HAIR ON HIS HEAD&MDASH;NONE TO SPEAK OF AT LEAST&MDASH;NOTHING
      BUT A SMALL SCALP-KNOT TWISTED UP ON HIS FOREHEAD. hIS BALD PURPLISH HEAD
      NOW LOOKED FOR ALL THE WORLD LIKE A MILDEWED SKULL. hAD NOT THE STRANGER
      STOOD BETWEEN ME AND THE DOOR, i WOULD HAVE BOLTED OUT OF IT QUICKER THAN
      EVER i BOLTED A DINNER.
    </P>
    <P>
      eVEN AS IT WAS, i THOUGHT SOMETHING OF SLIPPING OUT OF THE WINDOW, BUT IT
      WAS THE SECOND FLOOR BACK. i AM NO COWARD, BUT WHAT TO MAKE OF THIS
      HEAD-PEDDLING PURPLE RASCAL ALTOGETHER PASSED MY COMPREHENSION. iGNORANCE
      IS THE PARENT OF FEAR, AND BEING COMPLETELY NONPLUSSED AND CONFOUNDED
      ABOUT THE STRANGER, i CONFESS i WAS NOW AS MUCH AFRAID OF HIM AS IF IT WAS
      THE DEVIL HIMSELF WHO HAD THUS BROKEN INTO MY ROOM AT THE DEAD OF NIGHT.
      iN FACT, i WAS SO AFRAID OF HIM THAT i WAS NOT GAME ENOUGH JUST THEN TO
      ADDRESS HIM, AND DEMAND A SATISFACTORY ANSWER CONCERNING WHAT SEEMED
      INEXPLICABLE IN HIM.
    </P>
    <P>
      mEANWHILE, HE CONTINUED THE BUSINESS OF UNDRESSING, AND AT LAST SHOWED HIS
      CHEST AND ARMS. aS i LIVE, THESE COVERED PARTS OF HIM WERE CHECKERED WITH
      THE SAME SQUARES AS HIS FACE; HIS BACK, TOO, WAS ALL OVER THE SAME DARK
      SQUARES; HE SEEMED TO HAVE BEEN IN A tHIRTY yEARS&RSQUO; wAR, AND JUST ESCAPED
      FROM IT WITH A STICKING-PLASTER SHIRT. sTILL MORE, HIS VERY LEGS WERE
      MARKED, AS IF A PARCEL OF DARK GREEN FROGS WERE RUNNING UP THE TRUNKS OF
      YOUNG PALMS. iT WAS NOW QUITE PLAIN THAT HE MUST BE SOME ABOMINABLE SAVAGE
      OR OTHER SHIPPED ABOARD OF A WHALEMAN IN THE sOUTH sEAS, AND SO LANDED IN
      THIS cHRISTIAN COUNTRY. i QUAKED TO THINK OF IT. a PEDDLER OF HEADS TOO&MDASH;PERHAPS
      THE HEADS OF HIS OWN BROTHERS. hE MIGHT TAKE A FANCY TO MINE&MDASH;HEAVENS!
      LOOK AT THAT TOMAHAWK!
    </P>
    <P>
      bUT THERE WAS NO TIME FOR SHUDDERING, FOR NOW THE SAVAGE WENT ABOUT
      SOMETHING THAT COMPLETELY FASCINATED MY ATTENTION, AND CONVINCED ME THAT
      HE MUST INDEED BE A HEATHEN. gOING TO HIS HEAVY GREGO, OR WRAPALL, OR
      DREADNAUGHT, WHICH HE HAD PREVIOUSLY HUNG ON A CHAIR, HE FUMBLED IN THE
      POCKETS, AND PRODUCED AT LENGTH A CURIOUS LITTLE DEFORMED IMAGE WITH A
      HUNCH ON ITS BACK, AND EXACTLY THE COLOUR OF A THREE DAYS&RSQUO; OLD cONGO BABY.
      rEMEMBERING THE EMBALMED HEAD, AT FIRST i ALMOST THOUGHT THAT THIS BLACK
      MANIKIN WAS A REAL BABY PRESERVED IN SOME SIMILAR MANNER. bUT SEEING THAT
      IT WAS NOT AT ALL LIMBER, AND THAT IT GLISTENED A GOOD DEAL LIKE POLISHED
      EBONY, i CONCLUDED THAT IT MUST BE NOTHING BUT A WOODEN IDOL, WHICH INDEED
      IT PROVED TO BE. fOR NOW THE SAVAGE GOES UP TO THE EMPTY FIRE-PLACE, AND
      REMOVING THE PAPERED FIRE-BOARD, SETS UP THIS LITTLE HUNCH-BACKED IMAGE,
      LIKE A TENPIN, BETWEEN THE ANDIRONS. tHE CHIMNEY JAMBS AND ALL THE BRICKS
      INSIDE WERE VERY SOOTY, SO THAT i THOUGHT THIS FIRE-PLACE MADE A VERY
      APPROPRIATE LITTLE SHRINE OR CHAPEL FOR HIS cONGO IDOL.
    </P>
    <P>
      i NOW SCREWED MY EYES HARD TOWARDS THE HALF HIDDEN IMAGE, FEELING BUT ILL
      AT EASE MEANTIME&MDASH;TO SEE WHAT WAS NEXT TO FOLLOW. fIRST HE TAKES
      ABOUT A DOUBLE HANDFUL OF SHAVINGS OUT OF HIS GREGO POCKET, AND PLACES
      THEM CAREFULLY BEFORE THE IDOL; THEN LAYING A BIT OF SHIP BISCUIT ON TOP
      AND APPLYING THE FLAME FROM THE LAMP, HE KINDLED THE SHAVINGS INTO A
      SACRIFICIAL BLAZE. pRESENTLY, AFTER MANY HASTY SNATCHES INTO THE FIRE, AND
      STILL HASTIER WITHDRAWALS OF HIS FINGERS (WHEREBY HE SEEMED TO BE
      SCORCHING THEM BADLY), HE AT LAST SUCCEEDED IN DRAWING OUT THE BISCUIT;
      THEN BLOWING OFF THE HEAT AND ASHES A LITTLE, HE MADE A POLITE OFFER OF IT
      TO THE LITTLE NEGRO. bUT THE LITTLE DEVIL DID NOT SEEM TO FANCY SUCH DRY
      SORT OF FARE AT ALL; HE NEVER MOVED HIS LIPS. aLL THESE STRANGE ANTICS
      WERE ACCOMPANIED BY STILL STRANGER GUTTURAL NOISES FROM THE DEVOTEE, WHO
      SEEMED TO BE PRAYING IN A SING-SONG OR ELSE SINGING SOME PAGAN PSALMODY OR
      OTHER, DURING WHICH HIS FACE TWITCHED ABOUT IN THE MOST UNNATURAL MANNER.
      aT LAST EXTINGUISHING THE FIRE, HE TOOK THE IDOL UP VERY UNCEREMONIOUSLY,
      AND BAGGED IT AGAIN IN HIS GREGO POCKET AS CARELESSLY AS IF HE WERE A
      SPORTSMAN BAGGING A DEAD WOODCOCK.
    </P>
    <P>
      aLL THESE QUEER PROCEEDINGS INCREASED MY UNCOMFORTABLENESS, AND SEEING HIM
      NOW EXHIBITING STRONG SYMPTOMS OF CONCLUDING HIS BUSINESS OPERATIONS, AND
      JUMPING INTO BED WITH ME, i THOUGHT IT WAS HIGH TIME, NOW OR NEVER, BEFORE
      THE LIGHT WAS PUT OUT, TO BREAK THE SPELL IN WHICH i HAD SO LONG BEEN
      BOUND.
    </P>
    <P>
      bUT THE INTERVAL i SPENT IN DELIBERATING WHAT TO SAY, WAS A FATAL ONE.
      tAKING UP HIS TOMAHAWK FROM THE TABLE, HE EXAMINED THE HEAD OF IT FOR AN
      INSTANT, AND THEN HOLDING IT TO THE LIGHT, WITH HIS MOUTH AT THE HANDLE,
      HE PUFFED OUT GREAT CLOUDS OF TOBACCO SMOKE. tHE NEXT MOMENT THE LIGHT WAS
      EXTINGUISHED, AND THIS WILD CANNIBAL, TOMAHAWK BETWEEN HIS TEETH, SPRANG
      INTO BED WITH ME. i SANG OUT, i COULD NOT HELP IT NOW; AND GIVING A SUDDEN
      GRUNT OF ASTONISHMENT HE BEGAN FEELING ME.
    </P>
    <P>
      sTAMMERING OUT SOMETHING, i KNEW NOT WHAT, i ROLLED AWAY FROM HIM AGAINST
      THE WALL, AND THEN CONJURED HIM, WHOEVER OR WHATEVER HE MIGHT BE, TO KEEP
      QUIET, AND LET ME GET UP AND LIGHT THE LAMP AGAIN. bUT HIS GUTTURAL
      RESPONSES SATISFIED ME AT ONCE THAT HE BUT ILL COMPREHENDED MY MEANING.
    </P>
    <P>
      &LDQUO;wHO-E DEBEL YOU?&RDQUO;&MDASH;HE AT LAST SAID&MDASH;&LDQUO;YOU NO SPEAK-E, DAM-ME, i
      KILL-E.&RDQUO; aND SO SAYING THE LIGHTED TOMAHAWK BEGAN FLOURISHING ABOUT ME IN
      THE DARK.
    </P>
    <P>
      &LDQUO;lANDLORD, FOR gOD&RSQUO;S SAKE, pETER cOFFIN!&RDQUO; SHOUTED i. &LDQUO;lANDLORD! wATCH!
      cOFFIN! aNGELS! SAVE ME!&RDQUO;
     </P>
    <P>
      &LDQUO;sPEAK-E! TELL-EE ME WHO-EE BE, OR DAM-ME, i KILL-E!&RDQUO; AGAIN GROWLED THE
      CANNIBAL, WHILE HIS HORRID FLOURISHINGS OF THE TOMAHAWK SCATTERED THE HOT
      TOBACCO ASHES ABOUT ME TILL i THOUGHT MY LINEN WOULD GET ON FIRE. bUT
      THANK HEAVEN, AT THAT MOMENT THE LANDLORD CAME INTO THE ROOM LIGHT IN
      HAND, AND LEAPING FROM THE BED i RAN UP TO HIM.
    </P>
    <P>
      &LDQUO;dON&RSQUO;T BE AFRAID NOW,&RDQUO; SAID HE, GRINNING AGAIN, &LDQUO;qUEEQUEG HERE WOULDN&RSQUO;T
      HARM A HAIR OF YOUR HEAD.&RDQUO;
     </P>
    <P>
      &LDQUO;sTOP YOUR GRINNING,&RDQUO; SHOUTED i, &LDQUO;AND WHY DIDN&RSQUO;T YOU TELL ME THAT THAT
      INFERNAL HARPOONEER WAS A CANNIBAL?&RDQUO;
     </P>
    <P>
      &LDQUO;i THOUGHT YE KNOW&RSQUO;D IT;&MDASH;DIDN&RSQUO;T i TELL YE, HE WAS A PEDDLIN&RSQUO; HEADS
      AROUND TOWN?&MDASH;BUT TURN FLUKES AGAIN AND GO TO SLEEP. qUEEQUEG, LOOK
      HERE&MDASH;YOU SABBEE ME, i SABBEE&MDASH;YOU THIS MAN SLEEPE YOU&MDASH;YOU
      SABBEE?&RDQUO;
     </P>
    <P>
      &LDQUO;mE SABBEE PLENTY&RDQUO;&MDASH;GRUNTED qUEEQUEG, PUFFING AWAY AT HIS PIPE AND
      SITTING UP IN BED.
    </P>
    <P>
      &LDQUO;yOU GETTEE IN,&RDQUO; HE ADDED, MOTIONING TO ME WITH HIS TOMAHAWK, AND THROWING
      THE CLOTHES TO ONE SIDE. hE REALLY DID THIS IN NOT ONLY A CIVIL BUT A
      REALLY KIND AND CHARITABLE WAY. i STOOD LOOKING AT HIM A MOMENT. fOR ALL
      HIS TATTOOINGS HE WAS ON THE WHOLE A CLEAN, COMELY LOOKING CANNIBAL.
      wHAT&RSQUO;S ALL THIS FUSS i HAVE BEEN MAKING ABOUT, THOUGHT i TO MYSELF&MDASH;THE
      MAN&RSQUO;S A HUMAN BEING JUST AS i AM: HE HAS JUST AS MUCH REASON TO FEAR ME,
      AS i HAVE TO BE AFRAID OF HIM. bETTER SLEEP WITH A SOBER CANNIBAL THAN A
      DRUNKEN cHRISTIAN.
    </P>
    <P>
      &LDQUO;lANDLORD,&RDQUO; SAID i, &LDQUO;TELL HIM TO STASH HIS TOMAHAWK THERE, OR PIPE, OR
      WHATEVER YOU CALL IT; TELL HIM TO STOP SMOKING, IN SHORT, AND i WILL TURN
      IN WITH HIM. bUT i DON&RSQUO;T FANCY HAVING A MAN SMOKING IN BED WITH ME. iT&RSQUO;S
      DANGEROUS. bESIDES, i AIN&RSQUO;T INSURED.&RDQUO;
     </P>
    <P>
      tHIS BEING TOLD TO qUEEQUEG, HE AT ONCE COMPLIED, AND AGAIN POLITELY
      MOTIONED ME TO GET INTO BED&MDASH;ROLLING OVER TO ONE SIDE AS MUCH AS TO
      SAY&MDASH;&LDQUO;i WON&RSQUO;T TOUCH A LEG OF YE.&RDQUO;
     </P>
    <P>
      &LDQUO;gOOD NIGHT, LANDLORD,&RDQUO; SAID i, &LDQUO;YOU MAY GO.&RDQUO;
     </P>
    <P>
      i TURNED IN, AND NEVER SLEPT BETTER IN MY LIFE.
    </P>
    <P>
      <A NAME="LINK2hch0004" ID="LINK2hch0004">
      <!--  h2 ANCHOR --> </A>
    </P>
    <DIV STYLE="HEIGHT: 4EM;">
      <BR /><BR /><BR /><BR />
    </DIV>
    <H2>
      chapter 4. tHE cOUNTERPANE.
    </H2>
    <P>
      uPON WAKING NEXT MORNING ABOUT DAYLIGHT, i FOUND qUEEQUEG&RSQUO;S ARM THROWN
      OVER ME IN THE MOST LOVING AND AFFECTIONATE MANNER. yOU HAD ALMOST THOUGHT
      i HAD BEEN HIS WIFE. tHE COUNTERPANE WAS OF PATCHWORK, FULL OF ODD LITTLE
      PARTI-COLOURED SQUARES AND TRIANGLES; AND THIS ARM OF HIS TATTOOED ALL
      OVER WITH AN INTERMINABLE cRETAN LABYRINTH OF A FIGURE, NO TWO PARTS OF
      WHICH WERE OF ONE PRECISE SHADE&MDASH;OWING i SUPPOSE TO HIS KEEPING HIS
      ARM AT SEA UNMETHODICALLY IN SUN AND SHADE, HIS SHIRT SLEEVES IRREGULARLY
      ROLLED UP AT VARIOUS TIMES&MDASH;THIS SAME ARM OF HIS, i SAY, LOOKED FOR
      ALL THE WORLD LIKE A STRIP OF THAT SAME PATCHWORK QUILT. iNDEED, PARTLY
      LYING ON IT AS THE ARM DID WHEN i FIRST AWOKE, i COULD HARDLY TELL IT FROM
      THE QUILT, THEY SO BLENDED THEIR HUES TOGETHER; AND IT WAS ONLY BY THE
      SENSE OF WEIGHT AND PRESSURE THAT i COULD TELL THAT qUEEQUEG WAS HUGGING
      ME.
    </P>
    <P>
      mY SENSATIONS WERE STRANGE. lET ME TRY TO EXPLAIN THEM. wHEN i WAS A
      CHILD, i WELL REMEMBER A SOMEWHAT SIMILAR CIRCUMSTANCE THAT BEFELL ME;
      WHETHER IT WAS A REALITY OR A DREAM, i NEVER COULD ENTIRELY SETTLE. tHE
      CIRCUMSTANCE WAS THIS. i HAD BEEN CUTTING UP SOME CAPER OR OTHER&MDASH;i
      THINK IT WAS TRYING TO CRAWL UP THE CHIMNEY, AS i HAD SEEN A LITTLE SWEEP
      DO A FEW DAYS PREVIOUS; AND MY STEPMOTHER WHO, SOMEHOW OR OTHER, WAS ALL
      THE TIME WHIPPING ME, OR SENDING ME TO BED SUPPERLESS,&MDASH;MY MOTHER
      DRAGGED ME BY THE LEGS OUT OF THE CHIMNEY AND PACKED ME OFF TO BED, THOUGH
      IT WAS ONLY TWO O&RSQUO;CLOCK IN THE AFTERNOON OF THE 21ST jUNE, THE LONGEST DAY
      IN THE YEAR IN OUR HEMISPHERE. i FELT DREADFULLY. bUT THERE WAS NO HELP
      FOR IT, SO UP STAIRS i WENT TO MY LITTLE ROOM IN THE THIRD FLOOR,
      UNDRESSED MYSELF AS SLOWLY AS POSSIBLE SO AS TO KILL TIME, AND WITH A
      BITTER SIGH GOT BETWEEN THE SHEETS.
    </P>
    <P>
      i LAY THERE DISMALLY CALCULATING THAT SIXTEEN ENTIRE HOURS MUST ELAPSE
      BEFORE i COULD HOPE FOR A RESURRECTION. sIXTEEN HOURS IN BED! THE SMALL OF
      MY BACK ACHED TO THINK OF IT. aND IT WAS SO LIGHT TOO; THE SUN SHINING IN
      AT THE WINDOW, AND A GREAT RATTLING OF COACHES IN THE STREETS, AND THE
      SOUND OF GAY VOICES ALL OVER THE HOUSE. i FELT WORSE AND WORSE&MDASH;AT
      LAST i GOT UP, DRESSED, AND SOFTLY GOING DOWN IN MY STOCKINGED FEET,
      SOUGHT OUT MY STEPMOTHER, AND SUDDENLY THREW MYSELF AT HER FEET,
      BESEECHING HER AS A PARTICULAR FAVOUR TO GIVE ME A GOOD SLIPPERING FOR MY
      MISBEHAVIOUR; ANYTHING INDEED BUT CONDEMNING ME TO LIE ABED SUCH AN
      UNENDURABLE LENGTH OF TIME. bUT SHE WAS THE BEST AND MOST CONSCIENTIOUS OF
      STEPMOTHERS, AND BACK i HAD TO GO TO MY ROOM. fOR SEVERAL HOURS i LAY
      THERE BROAD AWAKE, FEELING A GREAT DEAL WORSE THAN i HAVE EVER DONE SINCE,
      EVEN FROM THE GREATEST SUBSEQUENT MISFORTUNES. aT LAST i MUST HAVE FALLEN
      INTO A TROUBLED NIGHTMARE OF A DOZE; AND SLOWLY WAKING FROM IT&MDASH;HALF
      STEEPED IN DREAMS&MDASH;i OPENED MY EYES, AND THE BEFORE SUN-LIT ROOM WAS
      NOW WRAPPED IN OUTER DARKNESS. iNSTANTLY i FELT A SHOCK RUNNING THROUGH
      ALL MY FRAME; NOTHING WAS TO BE SEEN, AND NOTHING WAS TO BE HEARD; BUT A
      SUPERNATURAL HAND SEEMED PLACED IN MINE. mY ARM HUNG OVER THE COUNTERPANE,
      AND THE NAMELESS, UNIMAGINABLE, SILENT FORM OR PHANTOM, TO WHICH THE HAND
      BELONGED, SEEMED CLOSELY SEATED BY MY BED-SIDE. fOR WHAT SEEMED AGES PILED
      ON AGES, i LAY THERE, FROZEN WITH THE MOST AWFUL FEARS, NOT DARING TO DRAG
      AWAY MY HAND; YET EVER THINKING THAT IF i COULD BUT STIR IT ONE SINGLE
      INCH, THE HORRID SPELL WOULD BE BROKEN. i KNEW NOT HOW THIS CONSCIOUSNESS
      AT LAST GLIDED AWAY FROM ME; BUT WAKING IN THE MORNING, i SHUDDERINGLY
      REMEMBERED IT ALL, AND FOR DAYS AND WEEKS AND MONTHS AFTERWARDS i LOST
      MYSELF IN CONFOUNDING ATTEMPTS TO EXPLAIN THE MYSTERY. nAY, TO THIS VERY
      HOUR, i OFTEN PUZZLE MYSELF WITH IT.
    </P>
    <P>
      nOW, TAKE AWAY THE AWFUL FEAR, AND MY SENSATIONS AT FEELING THE
      SUPERNATURAL HAND IN MINE WERE VERY SIMILAR, IN THEIR STRANGENESS, TO
      THOSE WHICH i EXPERIENCED ON WAKING UP AND SEEING qUEEQUEG&RSQUO;S PAGAN ARM
      THROWN ROUND ME. bUT AT LENGTH ALL THE PAST NIGHT&RSQUO;S EVENTS SOBERLY
      RECURRED, ONE BY ONE, IN FIXED REALITY, AND THEN i LAY ONLY ALIVE TO THE
      COMICAL PREDICAMENT. fOR THOUGH i TRIED TO MOVE HIS ARM&MDASH;UNLOCK HIS
      BRIDEGROOM CLASP&MDASH;YET, SLEEPING AS HE WAS, HE STILL HUGGED ME
      TIGHTLY, AS THOUGH NAUGHT BUT DEATH SHOULD PART US TWAIN. i NOW STROVE TO
      ROUSE HIM&MDASH;&LDQUO;qUEEQUEG!&RDQUO;&MDASH;BUT HIS ONLY ANSWER WAS A SNORE. i THEN
      ROLLED OVER, MY NECK FEELING AS IF IT WERE IN A HORSE-COLLAR; AND SUDDENLY
      FELT A SLIGHT SCRATCH. tHROWING ASIDE THE COUNTERPANE, THERE LAY THE
      TOMAHAWK SLEEPING BY THE SAVAGE&RSQUO;S SIDE, AS IF IT WERE A HATCHET-FACED
      BABY. a PRETTY PICKLE, TRULY, THOUGHT i; ABED HERE IN A STRANGE HOUSE IN
      THE BROAD DAY, WITH A CANNIBAL AND A TOMAHAWK! &LDQUO;qUEEQUEG!&MDASH;IN THE
      NAME OF GOODNESS, qUEEQUEG, WAKE!&RDQUO; aT LENGTH, BY DINT OF MUCH WRIGGLING,
      AND LOUD AND INCESSANT EXPOSTULATIONS UPON THE UNBECOMINGNESS OF HIS
      HUGGING A FELLOW MALE IN THAT MATRIMONIAL SORT OF STYLE, i SUCCEEDED IN
      EXTRACTING A GRUNT; AND PRESENTLY, HE DREW BACK HIS ARM, SHOOK HIMSELF ALL
      OVER LIKE A nEWFOUNDLAND DOG JUST FROM THE WATER, AND SAT UP IN BED, STIFF
      AS A PIKE-STAFF, LOOKING AT ME, AND RUBBING HIS EYES AS IF HE DID NOT
      ALTOGETHER REMEMBER HOW i CAME TO BE THERE, THOUGH A DIM CONSCIOUSNESS OF
      KNOWING SOMETHING ABOUT ME SEEMED SLOWLY DAWNING OVER HIM. mEANWHILE, i
      LAY QUIETLY EYEING HIM, HAVING NO SERIOUS MISGIVINGS NOW, AND BENT UPON
      NARROWLY OBSERVING SO CURIOUS A CREATURE. wHEN, AT LAST, HIS MIND SEEMED
      MADE UP TOUCHING THE CHARACTER OF HIS BEDFELLOW, AND HE BECAME, AS IT
      WERE, RECONCILED TO THE FACT; HE JUMPED OUT UPON THE FLOOR, AND BY CERTAIN
      SIGNS AND SOUNDS GAVE ME TO UNDERSTAND THAT, IF IT PLEASED ME, HE WOULD
      DRESS FIRST AND THEN LEAVE ME TO DRESS AFTERWARDS, LEAVING THE WHOLE
      APARTMENT TO MYSELF. tHINKS i, qUEEQUEG, UNDER THE CIRCUMSTANCES, THIS IS
      A VERY CIVILIZED OVERTURE; BUT, THE TRUTH IS, THESE SAVAGES HAVE AN INNATE
      SENSE OF DELICACY, SAY WHAT YOU WILL; IT IS MARVELLOUS HOW ESSENTIALLY
      POLITE THEY ARE. i PAY THIS PARTICULAR COMPLIMENT TO qUEEQUEG, BECAUSE HE
      TREATED ME WITH SO MUCH CIVILITY AND CONSIDERATION, WHILE i WAS GUILTY OF
      GREAT RUDENESS; STARING AT HIM FROM THE BED, AND WATCHING ALL HIS TOILETTE
      MOTIONS; FOR THE TIME MY CURIOSITY GETTING THE BETTER OF MY BREEDING.
      nEVERTHELESS, A MAN LIKE qUEEQUEG YOU DON&RSQUO;T SEE EVERY DAY, HE AND HIS WAYS
      WERE WELL WORTH UNUSUAL REGARDING.
    </P>
    <P>
      hE COMMENCED DRESSING AT TOP BY DONNING HIS BEAVER HAT, A VERY TALL ONE,
      BY THE BY, AND THEN&MDASH;STILL MINUS HIS TROWSERS&MDASH;HE HUNTED UP HIS
      BOOTS. wHAT UNDER THE HEAVENS HE DID IT FOR, i CANNOT TELL, BUT HIS NEXT
      MOVEMENT WAS TO CRUSH HIMSELF&MDASH;BOOTS IN HAND, AND HAT ON&MDASH;UNDER
      THE BED; WHEN, FROM SUNDRY VIOLENT GASPINGS AND STRAININGS, i INFERRED HE
      WAS HARD AT WORK BOOTING HIMSELF; THOUGH BY NO LAW OF PROPRIETY THAT i
      EVER HEARD OF, IS ANY MAN REQUIRED TO BE PRIVATE WHEN PUTTING ON HIS
      BOOTS. bUT qUEEQUEG, DO YOU SEE, WAS A CREATURE IN THE TRANSITION STAGE&MDASH;NEITHER
      CATERPILLAR NOR BUTTERFLY. hE WAS JUST ENOUGH CIVILIZED TO SHOW OFF HIS
      OUTLANDISHNESS IN THE STRANGEST POSSIBLE MANNERS. hIS EDUCATION WAS NOT
      YET COMPLETED. hE WAS AN UNDERGRADUATE. iF HE HAD NOT BEEN A SMALL DEGREE
      CIVILIZED, HE VERY PROBABLY WOULD NOT HAVE TROUBLED HIMSELF WITH BOOTS AT
      ALL; BUT THEN, IF HE HAD NOT BEEN STILL A SAVAGE, HE NEVER WOULD HAVE
      DREAMT OF GETTING UNDER THE BED TO PUT THEM ON. aT LAST, HE EMERGED WITH
      HIS HAT VERY MUCH DENTED AND CRUSHED DOWN OVER HIS EYES, AND BEGAN
      CREAKING AND LIMPING ABOUT THE ROOM, AS IF, NOT BEING MUCH ACCUSTOMED TO
      BOOTS, HIS PAIR OF DAMP, WRINKLED COWHIDE ONES&MDASH;PROBABLY NOT MADE TO
      ORDER EITHER&MDASH;RATHER PINCHED AND TORMENTED HIM AT THE FIRST GO OFF OF
      A BITTER COLD MORNING.
    </P>
    <P>
      sEEING, NOW, THAT THERE WERE NO CURTAINS TO THE WINDOW, AND THAT THE
      STREET BEING VERY NARROW, THE HOUSE OPPOSITE COMMANDED A PLAIN VIEW INTO
      THE ROOM, AND OBSERVING MORE AND MORE THE INDECOROUS FIGURE THAT qUEEQUEG
      MADE, STAVING ABOUT WITH LITTLE ELSE BUT HIS HAT AND BOOTS ON; i BEGGED
      HIM AS WELL AS i COULD, TO ACCELERATE HIS TOILET SOMEWHAT, AND
      PARTICULARLY TO GET INTO HIS PANTALOONS AS SOON AS POSSIBLE. hE COMPLIED,
      AND THEN PROCEEDED TO WASH HIMSELF. aT THAT TIME IN THE MORNING ANY
      cHRISTIAN WOULD HAVE WASHED HIS FACE; BUT qUEEQUEG, TO MY AMAZEMENT,
      CONTENTED HIMSELF WITH RESTRICTING HIS ABLUTIONS TO HIS CHEST, ARMS, AND
      HANDS. hE THEN DONNED HIS WAISTCOAT, AND TAKING UP A PIECE OF HARD SOAP ON
      THE WASH-STAND CENTRE TABLE, DIPPED IT INTO WATER AND COMMENCED LATHERING
      HIS FACE. i WAS WATCHING TO SEE WHERE HE KEPT HIS RAZOR, WHEN LO AND
      BEHOLD, HE TAKES THE HARPOON FROM THE BED CORNER, SLIPS OUT THE LONG
      WOODEN STOCK, UNSHEATHES THE HEAD, WHETS IT A LITTLE ON HIS BOOT, AND
      STRIDING UP TO THE BIT OF MIRROR AGAINST THE WALL, BEGINS A VIGOROUS
      SCRAPING, OR RATHER HARPOONING OF HIS CHEEKS. tHINKS i, qUEEQUEG, THIS IS
      USING rOGERS&RSQUO;S BEST CUTLERY WITH A VENGEANCE. aFTERWARDS i WONDERED THE
      LESS AT THIS OPERATION WHEN i CAME TO KNOW OF WHAT FINE STEEL THE HEAD OF
      A HARPOON IS MADE, AND HOW EXCEEDINGLY SHARP THE LONG STRAIGHT EDGES ARE
      ALWAYS KEPT.
    </P>
    <P>
      tHE REST OF HIS TOILET WAS SOON ACHIEVED, AND HE PROUDLY MARCHED OUT OF
      THE ROOM, WRAPPED UP IN HIS GREAT PILOT MONKEY JACKET, AND SPORTING HIS
      HARPOON LIKE A MARSHAL&RSQUO;S BATON.
    </P>
    <P>
      <A NAME="LINK2hch0005" ID="LINK2hch0005">
      <!--  h2 ANCHOR --> </A>
    </P>
    <DIV STYLE="HEIGHT: 4EM;">
      <BR /><BR /><BR /><BR />
    </DIV>
    <H2>
      chapter 5. bREAKFAST.
    </H2>
    <P>
      i QUICKLY FOLLOWED SUIT, AND DESCENDING INTO THE BAR-ROOM ACCOSTED THE
      GRINNING LANDLORD VERY PLEASANTLY. i CHERISHED NO MALICE TOWARDS HIM,
      THOUGH HE HAD BEEN SKYLARKING WITH ME NOT A LITTLE IN THE MATTER OF MY
      BEDFELLOW.
    </P>
    <P>
      hOWEVER, A GOOD LAUGH IS A MIGHTY GOOD THING, AND RATHER TOO SCARCE A GOOD
      THING; THE MORE&RSQUO;S THE PITY. sO, IF ANY ONE MAN, IN HIS OWN PROPER PERSON,
      AFFORD STUFF FOR A GOOD JOKE TO ANYBODY, LET HIM NOT BE BACKWARD, BUT LET
      HIM CHEERFULLY ALLOW HIMSELF TO SPEND AND BE SPENT IN THAT WAY. aND THE
      MAN THAT HAS ANYTHING BOUNTIFULLY LAUGHABLE ABOUT HIM, BE SURE THERE IS
      MORE IN THAT MAN THAN YOU PERHAPS THINK FOR.
    </P>
    <P>
      tHE BAR-ROOM WAS NOW FULL OF THE BOARDERS WHO HAD BEEN DROPPING IN THE
      NIGHT PREVIOUS, AND WHOM i HAD NOT AS YET HAD A GOOD LOOK AT. tHEY WERE
      NEARLY ALL WHALEMEN; CHIEF MATES, AND SECOND MATES, AND THIRD MATES, AND
      SEA CARPENTERS, AND SEA COOPERS, AND SEA BLACKSMITHS, AND HARPOONEERS, AND
      SHIP KEEPERS; A BROWN AND BRAWNY COMPANY, WITH BOSKY BEARDS; AN UNSHORN,
      SHAGGY SET, ALL WEARING MONKEY JACKETS FOR MORNING GOWNS.
    </P>
    <P>
      yOU COULD PRETTY PLAINLY TELL HOW LONG EACH ONE HAD BEEN ASHORE. tHIS
      YOUNG FELLOW&RSQUO;S HEALTHY CHEEK IS LIKE A SUN-TOASTED PEAR IN HUE, AND WOULD
      SEEM TO SMELL ALMOST AS MUSKY; HE CANNOT HAVE BEEN THREE DAYS LANDED FROM
      HIS iNDIAN VOYAGE. tHAT MAN NEXT HIM LOOKS A FEW SHADES LIGHTER; YOU MIGHT
      SAY A TOUCH OF SATIN WOOD IS IN HIM. iN THE COMPLEXION OF A THIRD STILL
      LINGERS A TROPIC TAWN, BUT SLIGHTLY BLEACHED WITHAL; <I>HE</I> DOUBTLESS HAS
      TARRIED WHOLE WEEKS ASHORE. bUT WHO COULD SHOW A CHEEK LIKE qUEEQUEG?
      WHICH, BARRED WITH VARIOUS TINTS, SEEMED LIKE THE aNDES&RSQUO; WESTERN SLOPE, TO
      SHOW FORTH IN ONE ARRAY, CONTRASTING CLIMATES, ZONE BY ZONE.
    </P>
    <P>
      &LDQUO;gRUB, HO!&RDQUO; NOW CRIED THE LANDLORD, FLINGING OPEN A DOOR, AND IN WE WENT
      TO BREAKFAST.
    </P>
    <P>
      tHEY SAY THAT MEN WHO HAVE SEEN THE WORLD, THEREBY BECOME QUITE AT EASE IN
      MANNER, QUITE SELF-POSSESSED IN COMPANY. nOT ALWAYS, THOUGH: lEDYARD, THE
      GREAT nEW eNGLAND TRAVELLER, AND mUNGO pARK, THE sCOTCH ONE; OF ALL MEN,
      THEY POSSESSED THE LEAST ASSURANCE IN THE PARLOR. bUT PERHAPS THE MERE
      CROSSING OF sIBERIA IN A SLEDGE DRAWN BY DOGS AS lEDYARD DID, OR THE
      TAKING A LONG SOLITARY WALK ON AN EMPTY STOMACH, IN THE NEGRO HEART OF
      aFRICA, WHICH WAS THE SUM OF POOR mUNGO&RSQUO;S PERFORMANCES&MDASH;THIS KIND OF
      TRAVEL, i SAY, MAY NOT BE THE VERY BEST MODE OF ATTAINING A HIGH SOCIAL
      POLISH. sTILL, FOR THE MOST PART, THAT SORT OF THING IS TO BE HAD
      ANYWHERE.
    </P>
    <P>
      tHESE REFLECTIONS JUST HERE ARE OCCASIONED BY THE CIRCUMSTANCE THAT AFTER
      WE WERE ALL SEATED AT THE TABLE, AND i WAS PREPARING TO HEAR SOME GOOD
      STORIES ABOUT WHALING; TO MY NO SMALL SURPRISE, NEARLY EVERY MAN
      MAINTAINED A PROFOUND SILENCE. aND NOT ONLY THAT, BUT THEY LOOKED
      EMBARRASSED. yES, HERE WERE A SET OF SEA-DOGS, MANY OF WHOM WITHOUT THE
      SLIGHTEST BASHFULNESS HAD BOARDED GREAT WHALES ON THE HIGH SEAS&MDASH;ENTIRE
      STRANGERS TO THEM&MDASH;AND DUELLED THEM DEAD WITHOUT WINKING; AND YET,
      HERE THEY SAT AT A SOCIAL BREAKFAST TABLE&MDASH;ALL OF THE SAME CALLING,
      ALL OF KINDRED TASTES&MDASH;LOOKING ROUND AS SHEEPISHLY AT EACH OTHER AS
      THOUGH THEY HAD NEVER BEEN OUT OF SIGHT OF SOME SHEEPFOLD AMONG THE gREEN
      mOUNTAINS. a CURIOUS SIGHT; THESE BASHFUL BEARS, THESE TIMID WARRIOR
      WHALEMEN!
    </P>
    <P>
      bUT AS FOR qUEEQUEG&MDASH;WHY, qUEEQUEG SAT THERE AMONG THEM&MDASH;AT THE
      HEAD OF THE TABLE, TOO, IT SO CHANCED; AS COOL AS AN ICICLE. tO BE SURE i
      CANNOT SAY MUCH FOR HIS BREEDING. hIS GREATEST ADMIRER COULD NOT HAVE
      CORDIALLY JUSTIFIED HIS BRINGING HIS HARPOON INTO BREAKFAST WITH HIM, AND
      USING IT THERE WITHOUT CEREMONY; REACHING OVER THE TABLE WITH IT, TO THE
      IMMINENT JEOPARDY OF MANY HEADS, AND GRAPPLING THE BEEFSTEAKS TOWARDS HIM.
      bUT <I>THAT</I> WAS CERTAINLY VERY COOLLY DONE BY HIM, AND EVERY ONE KNOWS THAT
      IN MOST PEOPLE&RSQUO;S ESTIMATION, TO DO ANYTHING COOLLY IS TO DO IT GENTEELLY.
    </P>
    <P>
      wE WILL NOT SPEAK OF ALL qUEEQUEG&RSQUO;S PECULIARITIES HERE; HOW HE ESCHEWED
      COFFEE AND HOT ROLLS, AND APPLIED HIS UNDIVIDED ATTENTION TO BEEFSTEAKS,
      DONE RARE. eNOUGH, THAT WHEN BREAKFAST WAS OVER HE WITHDREW LIKE THE REST
      INTO THE PUBLIC ROOM, LIGHTED HIS TOMAHAWK-PIPE, AND WAS SITTING THERE
      QUIETLY DIGESTING AND SMOKING WITH HIS INSEPARABLE HAT ON, WHEN i SALLIED
      OUT FOR A STROLL.
    </P>
    <P>
      <A NAME="LINK2hch0006" ID="LINK2hch0006">
      <!--  h2 ANCHOR --> </A>
    </P>
    <DIV STYLE="HEIGHT: 4EM;">
      <BR /><BR /><BR /><BR />
    </DIV>
    <H2>
      chapter 6. tHE sTREET.
    </H2>
    <P>
      iF i HAD BEEN ASTONISHED AT FIRST CATCHING A GLIMPSE OF SO OUTLANDISH AN
      INDIVIDUAL AS qUEEQUEG CIRCULATING AMONG THE POLITE SOCIETY OF A CIVILIZED
      TOWN, THAT ASTONISHMENT SOON DEPARTED UPON TAKING MY FIRST DAYLIGHT STROLL
      THROUGH THE STREETS OF nEW bEDFORD.
    </P>
    <P>
      iN THOROUGHFARES NIGH THE DOCKS, ANY CONSIDERABLE SEAPORT WILL FREQUENTLY
      OFFER TO VIEW THE QUEEREST LOOKING NONDESCRIPTS FROM FOREIGN PARTS. eVEN
      IN bROADWAY AND cHESTNUT STREETS, mEDITERRANEAN MARINERS WILL SOMETIMES
      JOSTLE THE AFFRIGHTED LADIES. rEGENT sTREET IS NOT UNKNOWN TO lASCARS AND
      mALAYS; AND AT bOMBAY, IN THE aPOLLO gREEN, LIVE yANKEES HAVE OFTEN SCARED
      THE NATIVES. bUT nEW bEDFORD BEATS ALL wATER sTREET AND wAPPING. iN THESE
      LAST-MENTIONED HAUNTS YOU SEE ONLY SAILORS; BUT IN nEW bEDFORD, ACTUAL
      CANNIBALS STAND CHATTING AT STREET CORNERS; SAVAGES OUTRIGHT; MANY OF WHOM
      YET CARRY ON THEIR BONES UNHOLY FLESH. iT MAKES A STRANGER STARE.
    </P>
    <P>
      bUT, BESIDES THE fEEGEEANS, tONGATOBOOARRS, eRROMANGGOANS, pANNANGIANS,
      AND bRIGHGGIANS, AND, BESIDES THE WILD SPECIMENS OF THE WHALING-CRAFT
      WHICH UNHEEDED REEL ABOUT THE STREETS, YOU WILL SEE OTHER SIGHTS STILL
      MORE CURIOUS, CERTAINLY MORE COMICAL. tHERE WEEKLY ARRIVE IN THIS TOWN
      SCORES OF GREEN vERMONTERS AND nEW hAMPSHIRE MEN, ALL ATHIRST FOR GAIN AND
      GLORY IN THE FISHERY. tHEY ARE MOSTLY YOUNG, OF STALWART FRAMES; FELLOWS
      WHO HAVE FELLED FORESTS, AND NOW SEEK TO DROP THE AXE AND SNATCH THE
      WHALE-LANCE. mANY ARE AS GREEN AS THE gREEN mOUNTAINS WHENCE THEY CAME. iN
      SOME THINGS YOU WOULD THINK THEM BUT A FEW HOURS OLD. lOOK THERE! THAT
      CHAP STRUTTING ROUND THE CORNER. hE WEARS A BEAVER HAT AND SWALLOW-TAILED
      COAT, GIRDLED WITH A SAILOR-BELT AND SHEATH-KNIFE. hERE COMES ANOTHER WITH
      A SOU&RSQUO;-WESTER AND A BOMBAZINE CLOAK.
    </P>
    <P>
      nO TOWN-BRED DANDY WILL COMPARE WITH A COUNTRY-BRED ONE&MDASH;i MEAN A
      DOWNRIGHT BUMPKIN DANDY&MDASH;A FELLOW THAT, IN THE DOG-DAYS, WILL MOW HIS
      TWO ACRES IN BUCKSKIN GLOVES FOR FEAR OF TANNING HIS HANDS. nOW WHEN A
      COUNTRY DANDY LIKE THIS TAKES IT INTO HIS HEAD TO MAKE A DISTINGUISHED
      REPUTATION, AND JOINS THE GREAT WHALE-FISHERY, YOU SHOULD SEE THE COMICAL
      THINGS HE DOES UPON REACHING THE SEAPORT. iN BESPEAKING HIS SEA-OUTFIT, HE
      ORDERS BELL-BUTTONS TO HIS WAISTCOATS; STRAPS TO HIS CANVAS TROWSERS. aH,
      POOR hAY-sEED! HOW BITTERLY WILL BURST THOSE STRAPS IN THE FIRST HOWLING
      GALE, WHEN THOU ART DRIVEN, STRAPS, BUTTONS, AND ALL, DOWN THE THROAT OF
      THE TEMPEST.
    </P>
    <P>
      bUT THINK NOT THAT THIS FAMOUS TOWN HAS ONLY HARPOONEERS, CANNIBALS, AND
      BUMPKINS TO SHOW HER VISITORS. nOT AT ALL. sTILL nEW bEDFORD IS A QUEER
      PLACE. hAD IT NOT BEEN FOR US WHALEMEN, THAT TRACT OF LAND WOULD THIS DAY
      PERHAPS HAVE BEEN IN AS HOWLING CONDITION AS THE COAST OF lABRADOR. aS IT
      IS, PARTS OF HER BACK COUNTRY ARE ENOUGH TO FRIGHTEN ONE, THEY LOOK SO
      BONY. tHE TOWN ITSELF IS PERHAPS THE DEAREST PLACE TO LIVE IN, IN ALL nEW
      eNGLAND. iT IS A LAND OF OIL, TRUE ENOUGH: BUT NOT LIKE cANAAN; A LAND,
      ALSO, OF CORN AND WINE. tHE STREETS DO NOT RUN WITH MILK; NOR IN THE
      SPRING-TIME DO THEY PAVE THEM WITH FRESH EGGS. yET, IN SPITE OF THIS,
      NOWHERE IN ALL aMERICA WILL YOU FIND MORE PATRICIAN-LIKE HOUSES; PARKS AND
      GARDENS MORE OPULENT, THAN IN nEW bEDFORD. wHENCE CAME THEY? HOW PLANTED
      UPON THIS ONCE SCRAGGY SCORIA OF A COUNTRY?
    </P>
    <P>
      gO AND GAZE UPON THE IRON EMBLEMATICAL HARPOONS ROUND YONDER LOFTY
      MANSION, AND YOUR QUESTION WILL BE ANSWERED. yES; ALL THESE BRAVE HOUSES
      AND FLOWERY GARDENS CAME FROM THE aTLANTIC, pACIFIC, AND iNDIAN OCEANS.
      oNE AND ALL, THEY WERE HARPOONED AND DRAGGED UP HITHER FROM THE BOTTOM OF
      THE SEA. cAN hERR aLEXANDER PERFORM A FEAT LIKE THAT?
    </P>
    <P>
      iN nEW bEDFORD, FATHERS, THEY SAY, GIVE WHALES FOR DOWERS TO THEIR
      DAUGHTERS, AND PORTION OFF THEIR NIECES WITH A FEW PORPOISES A-PIECE. yOU
      MUST GO TO nEW bEDFORD TO SEE A BRILLIANT WEDDING; FOR, THEY SAY, THEY
      HAVE RESERVOIRS OF OIL IN EVERY HOUSE, AND EVERY NIGHT RECKLESSLY BURN
      THEIR LENGTHS IN SPERMACETI CANDLES.
    </P>
    <P>
      iN SUMMER TIME, THE TOWN IS SWEET TO SEE; FULL OF FINE MAPLES&MDASH;LONG
      AVENUES OF GREEN AND GOLD. aND IN aUGUST, HIGH IN AIR, THE BEAUTIFUL AND
      BOUNTIFUL HORSE-CHESTNUTS, CANDELABRA-WISE, PROFFER THE PASSER-BY THEIR
      TAPERING UPRIGHT CONES OF CONGREGATED BLOSSOMS. sO OMNIPOTENT IS ART;
      WHICH IN MANY A DISTRICT OF nEW bEDFORD HAS SUPERINDUCED BRIGHT TERRACES
      OF FLOWERS UPON THE BARREN REFUSE ROCKS THROWN ASIDE AT CREATION&RSQUO;S FINAL
      DAY.
    </P>
    <P>
      aND THE WOMEN OF nEW bEDFORD, THEY BLOOM LIKE THEIR OWN RED ROSES. bUT
      ROSES ONLY BLOOM IN SUMMER; WHEREAS THE FINE CARNATION OF THEIR CHEEKS IS
      PERENNIAL AS SUNLIGHT IN THE SEVENTH HEAVENS. eLSEWHERE MATCH THAT BLOOM
      OF THEIRS, YE CANNOT, SAVE IN sALEM, WHERE THEY TELL ME THE YOUNG GIRLS
      BREATHE SUCH MUSK, THEIR SAILOR SWEETHEARTS SMELL THEM MILES OFF SHORE, AS
      THOUGH THEY WERE DRAWING NIGH THE ODOROUS mOLUCCAS INSTEAD OF THE
      pURITANIC SANDS.
    </P>
    <P>
      <A NAME="LINK2hch0007" ID="LINK2hch0007">
      <!--  h2 ANCHOR --> </A>
    </P>
    <DIV STYLE="HEIGHT: 4EM;">
      <BR /><BR /><BR /><BR />
    </DIV>
   `;

